// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_usercmd.proto

#ifndef PROTOBUF_INCLUDED_cs_5fusercmd_2eproto
#define PROTOBUF_INCLUDED_cs_5fusercmd_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "networkbasetypes.pb.h"
#include "usercmd.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cs_5fusercmd_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_cs_5fusercmd_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_cs_5fusercmd_2eproto();
class CSGOInputHistoryEntryPB;
class CSGOInputHistoryEntryPBDefaultTypeInternal;
extern CSGOInputHistoryEntryPBDefaultTypeInternal _CSGOInputHistoryEntryPB_default_instance_;
class CSGOInterpolationInfoPB;
class CSGOInterpolationInfoPBDefaultTypeInternal;
extern CSGOInterpolationInfoPBDefaultTypeInternal _CSGOInterpolationInfoPB_default_instance_;
class CSGOInterpolationInfoPB_CL;
class CSGOInterpolationInfoPB_CLDefaultTypeInternal;
extern CSGOInterpolationInfoPB_CLDefaultTypeInternal _CSGOInterpolationInfoPB_CL_default_instance_;
class CSGOUserCmdPB;
class CSGOUserCmdPBDefaultTypeInternal;
extern CSGOUserCmdPBDefaultTypeInternal _CSGOUserCmdPB_default_instance_;
namespace google {
namespace protobuf {
template<> ::CSGOInputHistoryEntryPB* Arena::CreateMaybeMessage<::CSGOInputHistoryEntryPB>(Arena*);
template<> ::CSGOInterpolationInfoPB* Arena::CreateMaybeMessage<::CSGOInterpolationInfoPB>(Arena*);
template<> ::CSGOInterpolationInfoPB_CL* Arena::CreateMaybeMessage<::CSGOInterpolationInfoPB_CL>(Arena*);
template<> ::CSGOUserCmdPB* Arena::CreateMaybeMessage<::CSGOUserCmdPB>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class CSGOInterpolationInfoPB final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSGOInterpolationInfoPB) */ {
 public:
  CSGOInterpolationInfoPB();
  virtual ~CSGOInterpolationInfoPB();

  CSGOInterpolationInfoPB(const CSGOInterpolationInfoPB& from);

  inline CSGOInterpolationInfoPB& operator=(const CSGOInterpolationInfoPB& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CSGOInterpolationInfoPB(CSGOInterpolationInfoPB&& from) noexcept
    : CSGOInterpolationInfoPB() {
    *this = ::std::move(from);
  }

  inline CSGOInterpolationInfoPB& operator=(CSGOInterpolationInfoPB&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CSGOInterpolationInfoPB& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CSGOInterpolationInfoPB* internal_default_instance() {
    return reinterpret_cast<const CSGOInterpolationInfoPB*>(
               &_CSGOInterpolationInfoPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CSGOInterpolationInfoPB* other);
  friend void swap(CSGOInterpolationInfoPB& a, CSGOInterpolationInfoPB& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CSGOInterpolationInfoPB* New() const final {
    return CreateMaybeMessage<CSGOInterpolationInfoPB>(nullptr);
  }

  CSGOInterpolationInfoPB* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CSGOInterpolationInfoPB>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CSGOInterpolationInfoPB& from);
  void MergeFrom(const CSGOInterpolationInfoPB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CSGOInterpolationInfoPB* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float frac = 3 [default = 0];
  bool has_frac() const;
  void clear_frac();
  static const int kFracFieldNumber = 3;
  float frac() const;
  void set_frac(float value);

  // optional int32 src_tick = 1 [default = -1];
  bool has_src_tick() const;
  void clear_src_tick();
  static const int kSrcTickFieldNumber = 1;
  ::google::protobuf::int32 src_tick() const;
  void set_src_tick(::google::protobuf::int32 value);

  // optional int32 dst_tick = 2 [default = -1];
  bool has_dst_tick() const;
  void clear_dst_tick();
  static const int kDstTickFieldNumber = 2;
  ::google::protobuf::int32 dst_tick() const;
  void set_dst_tick(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CSGOInterpolationInfoPB)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float frac_;
  ::google::protobuf::int32 src_tick_;
  ::google::protobuf::int32 dst_tick_;
  friend struct ::TableStruct_cs_5fusercmd_2eproto;
};
// -------------------------------------------------------------------

class CSGOInterpolationInfoPB_CL final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSGOInterpolationInfoPB_CL) */ {
 public:
  CSGOInterpolationInfoPB_CL();
  virtual ~CSGOInterpolationInfoPB_CL();

  CSGOInterpolationInfoPB_CL(const CSGOInterpolationInfoPB_CL& from);

  inline CSGOInterpolationInfoPB_CL& operator=(const CSGOInterpolationInfoPB_CL& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CSGOInterpolationInfoPB_CL(CSGOInterpolationInfoPB_CL&& from) noexcept
    : CSGOInterpolationInfoPB_CL() {
    *this = ::std::move(from);
  }

  inline CSGOInterpolationInfoPB_CL& operator=(CSGOInterpolationInfoPB_CL&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CSGOInterpolationInfoPB_CL& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CSGOInterpolationInfoPB_CL* internal_default_instance() {
    return reinterpret_cast<const CSGOInterpolationInfoPB_CL*>(
               &_CSGOInterpolationInfoPB_CL_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CSGOInterpolationInfoPB_CL* other);
  friend void swap(CSGOInterpolationInfoPB_CL& a, CSGOInterpolationInfoPB_CL& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CSGOInterpolationInfoPB_CL* New() const final {
    return CreateMaybeMessage<CSGOInterpolationInfoPB_CL>(nullptr);
  }

  CSGOInterpolationInfoPB_CL* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CSGOInterpolationInfoPB_CL>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CSGOInterpolationInfoPB_CL& from);
  void MergeFrom(const CSGOInterpolationInfoPB_CL& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CSGOInterpolationInfoPB_CL* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float frac = 3 [default = 0];
  bool has_frac() const;
  void clear_frac();
  static const int kFracFieldNumber = 3;
  float frac() const;
  void set_frac(float value);

  // @@protoc_insertion_point(class_scope:CSGOInterpolationInfoPB_CL)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float frac_;
  friend struct ::TableStruct_cs_5fusercmd_2eproto;
};
// -------------------------------------------------------------------

class CSGOInputHistoryEntryPB final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSGOInputHistoryEntryPB) */ {
 public:
  CSGOInputHistoryEntryPB();
  virtual ~CSGOInputHistoryEntryPB();

  CSGOInputHistoryEntryPB(const CSGOInputHistoryEntryPB& from);

  inline CSGOInputHistoryEntryPB& operator=(const CSGOInputHistoryEntryPB& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CSGOInputHistoryEntryPB(CSGOInputHistoryEntryPB&& from) noexcept
    : CSGOInputHistoryEntryPB() {
    *this = ::std::move(from);
  }

  inline CSGOInputHistoryEntryPB& operator=(CSGOInputHistoryEntryPB&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CSGOInputHistoryEntryPB& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CSGOInputHistoryEntryPB* internal_default_instance() {
    return reinterpret_cast<const CSGOInputHistoryEntryPB*>(
               &_CSGOInputHistoryEntryPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(CSGOInputHistoryEntryPB* other);
  friend void swap(CSGOInputHistoryEntryPB& a, CSGOInputHistoryEntryPB& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CSGOInputHistoryEntryPB* New() const final {
    return CreateMaybeMessage<CSGOInputHistoryEntryPB>(nullptr);
  }

  CSGOInputHistoryEntryPB* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CSGOInputHistoryEntryPB>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CSGOInputHistoryEntryPB& from);
  void MergeFrom(const CSGOInputHistoryEntryPB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CSGOInputHistoryEntryPB* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CMsgQAngle view_angles = 2;
  bool has_view_angles() const;
  void clear_view_angles();
  static const int kViewAnglesFieldNumber = 2;
  const ::CMsgQAngle& view_angles() const;
  ::CMsgQAngle* release_view_angles();
  ::CMsgQAngle* mutable_view_angles();
  void set_allocated_view_angles(::CMsgQAngle* view_angles);

  // optional .CSGOInterpolationInfoPB_CL cl_interp = 12;
  bool has_cl_interp() const;
  void clear_cl_interp();
  static const int kClInterpFieldNumber = 12;
  const ::CSGOInterpolationInfoPB_CL& cl_interp() const;
  ::CSGOInterpolationInfoPB_CL* release_cl_interp();
  ::CSGOInterpolationInfoPB_CL* mutable_cl_interp();
  void set_allocated_cl_interp(::CSGOInterpolationInfoPB_CL* cl_interp);

  // optional .CSGOInterpolationInfoPB sv_interp0 = 13;
  bool has_sv_interp0() const;
  void clear_sv_interp0();
  static const int kSvInterp0FieldNumber = 13;
  const ::CSGOInterpolationInfoPB& sv_interp0() const;
  ::CSGOInterpolationInfoPB* release_sv_interp0();
  ::CSGOInterpolationInfoPB* mutable_sv_interp0();
  void set_allocated_sv_interp0(::CSGOInterpolationInfoPB* sv_interp0);

  // optional .CSGOInterpolationInfoPB sv_interp1 = 14;
  bool has_sv_interp1() const;
  void clear_sv_interp1();
  static const int kSvInterp1FieldNumber = 14;
  const ::CSGOInterpolationInfoPB& sv_interp1() const;
  ::CSGOInterpolationInfoPB* release_sv_interp1();
  ::CSGOInterpolationInfoPB* mutable_sv_interp1();
  void set_allocated_sv_interp1(::CSGOInterpolationInfoPB* sv_interp1);

  // optional .CSGOInterpolationInfoPB player_interp = 15;
  bool has_player_interp() const;
  void clear_player_interp();
  static const int kPlayerInterpFieldNumber = 15;
  const ::CSGOInterpolationInfoPB& player_interp() const;
  ::CSGOInterpolationInfoPB* release_player_interp();
  ::CSGOInterpolationInfoPB* mutable_player_interp();
  void set_allocated_player_interp(::CSGOInterpolationInfoPB* player_interp);

  // optional .CMsgVector shoot_position = 66;
  bool has_shoot_position() const;
  void clear_shoot_position();
  static const int kShootPositionFieldNumber = 66;
  const ::CMsgVector& shoot_position() const;
  ::CMsgVector* release_shoot_position();
  ::CMsgVector* mutable_shoot_position();
  void set_allocated_shoot_position(::CMsgVector* shoot_position);

  // optional .CMsgVector target_head_pos_check = 67;
  bool has_target_head_pos_check() const;
  void clear_target_head_pos_check();
  static const int kTargetHeadPosCheckFieldNumber = 67;
  const ::CMsgVector& target_head_pos_check() const;
  ::CMsgVector* release_target_head_pos_check();
  ::CMsgVector* mutable_target_head_pos_check();
  void set_allocated_target_head_pos_check(::CMsgVector* target_head_pos_check);

  // optional .CMsgVector target_abs_pos_check = 68;
  bool has_target_abs_pos_check() const;
  void clear_target_abs_pos_check();
  static const int kTargetAbsPosCheckFieldNumber = 68;
  const ::CMsgVector& target_abs_pos_check() const;
  ::CMsgVector* release_target_abs_pos_check();
  ::CMsgVector* mutable_target_abs_pos_check();
  void set_allocated_target_abs_pos_check(::CMsgVector* target_abs_pos_check);

  // optional .CMsgQAngle target_abs_ang_check = 69;
  bool has_target_abs_ang_check() const;
  void clear_target_abs_ang_check();
  static const int kTargetAbsAngCheckFieldNumber = 69;
  const ::CMsgQAngle& target_abs_ang_check() const;
  ::CMsgQAngle* release_target_abs_ang_check();
  ::CMsgQAngle* mutable_target_abs_ang_check();
  void set_allocated_target_abs_ang_check(::CMsgQAngle* target_abs_ang_check);

  // optional int32 render_tick_count = 4;
  bool has_render_tick_count() const;
  void clear_render_tick_count();
  static const int kRenderTickCountFieldNumber = 4;
  ::google::protobuf::int32 render_tick_count() const;
  void set_render_tick_count(::google::protobuf::int32 value);

  // optional float render_tick_fraction = 5;
  bool has_render_tick_fraction() const;
  void clear_render_tick_fraction();
  static const int kRenderTickFractionFieldNumber = 5;
  float render_tick_fraction() const;
  void set_render_tick_fraction(float value);

  // optional int32 player_tick_count = 6;
  bool has_player_tick_count() const;
  void clear_player_tick_count();
  static const int kPlayerTickCountFieldNumber = 6;
  ::google::protobuf::int32 player_tick_count() const;
  void set_player_tick_count(::google::protobuf::int32 value);

  // optional float player_tick_fraction = 7;
  bool has_player_tick_fraction() const;
  void clear_player_tick_fraction();
  static const int kPlayerTickFractionFieldNumber = 7;
  float player_tick_fraction() const;
  void set_player_tick_fraction(float value);

  // optional int32 frame_number = 64;
  bool has_frame_number() const;
  void clear_frame_number();
  static const int kFrameNumberFieldNumber = 64;
  ::google::protobuf::int32 frame_number() const;
  void set_frame_number(::google::protobuf::int32 value);

  // optional int32 target_ent_index = 65 [default = -1];
  bool has_target_ent_index() const;
  void clear_target_ent_index();
  static const int kTargetEntIndexFieldNumber = 65;
  ::google::protobuf::int32 target_ent_index() const;
  void set_target_ent_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CSGOInputHistoryEntryPB)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::CMsgQAngle* view_angles_;
  ::CSGOInterpolationInfoPB_CL* cl_interp_;
  ::CSGOInterpolationInfoPB* sv_interp0_;
  ::CSGOInterpolationInfoPB* sv_interp1_;
  ::CSGOInterpolationInfoPB* player_interp_;
  ::CMsgVector* shoot_position_;
  ::CMsgVector* target_head_pos_check_;
  ::CMsgVector* target_abs_pos_check_;
  ::CMsgQAngle* target_abs_ang_check_;
  ::google::protobuf::int32 render_tick_count_;
  float render_tick_fraction_;
  ::google::protobuf::int32 player_tick_count_;
  float player_tick_fraction_;
  ::google::protobuf::int32 frame_number_;
  ::google::protobuf::int32 target_ent_index_;
  friend struct ::TableStruct_cs_5fusercmd_2eproto;
};
// -------------------------------------------------------------------

class CSGOUserCmdPB final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSGOUserCmdPB) */ {
 public:
  CSGOUserCmdPB();
  virtual ~CSGOUserCmdPB();

  CSGOUserCmdPB(const CSGOUserCmdPB& from);

  inline CSGOUserCmdPB& operator=(const CSGOUserCmdPB& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CSGOUserCmdPB(CSGOUserCmdPB&& from) noexcept
    : CSGOUserCmdPB() {
    *this = ::std::move(from);
  }

  inline CSGOUserCmdPB& operator=(CSGOUserCmdPB&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CSGOUserCmdPB& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CSGOUserCmdPB* internal_default_instance() {
    return reinterpret_cast<const CSGOUserCmdPB*>(
               &_CSGOUserCmdPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(CSGOUserCmdPB* other);
  friend void swap(CSGOUserCmdPB& a, CSGOUserCmdPB& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CSGOUserCmdPB* New() const final {
    return CreateMaybeMessage<CSGOUserCmdPB>(nullptr);
  }

  CSGOUserCmdPB* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CSGOUserCmdPB>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CSGOUserCmdPB& from);
  void MergeFrom(const CSGOUserCmdPB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CSGOUserCmdPB* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .CSGOInputHistoryEntryPB input_history = 2;
  int input_history_size() const;
  void clear_input_history();
  static const int kInputHistoryFieldNumber = 2;
  ::CSGOInputHistoryEntryPB* mutable_input_history(int index);
  ::google::protobuf::RepeatedPtrField< ::CSGOInputHistoryEntryPB >*
      mutable_input_history();
  const ::CSGOInputHistoryEntryPB& input_history(int index) const;
  ::CSGOInputHistoryEntryPB* add_input_history();
  const ::google::protobuf::RepeatedPtrField< ::CSGOInputHistoryEntryPB >&
      input_history() const;

  // optional .CBaseUserCmdPB base = 1;
  bool has_base() const;
  void clear_base();
  static const int kBaseFieldNumber = 1;
  const ::CBaseUserCmdPB& base() const;
  ::CBaseUserCmdPB* release_base();
  ::CBaseUserCmdPB* mutable_base();
  void set_allocated_base(::CBaseUserCmdPB* base);

  // optional bool left_hand_desired = 9 [default = false];
  bool has_left_hand_desired() const;
  void clear_left_hand_desired();
  static const int kLeftHandDesiredFieldNumber = 9;
  bool left_hand_desired() const;
  void set_left_hand_desired(bool value);

  // optional bool is_predicting_body_shot_fx = 11 [default = false];
  bool has_is_predicting_body_shot_fx() const;
  void clear_is_predicting_body_shot_fx();
  static const int kIsPredictingBodyShotFxFieldNumber = 11;
  bool is_predicting_body_shot_fx() const;
  void set_is_predicting_body_shot_fx(bool value);

  // optional bool is_predicting_head_shot_fx = 12 [default = false];
  bool has_is_predicting_head_shot_fx() const;
  void clear_is_predicting_head_shot_fx();
  static const int kIsPredictingHeadShotFxFieldNumber = 12;
  bool is_predicting_head_shot_fx() const;
  void set_is_predicting_head_shot_fx(bool value);

  // optional bool is_predicting_kill_ragdolls = 13 [default = false];
  bool has_is_predicting_kill_ragdolls() const;
  void clear_is_predicting_kill_ragdolls();
  static const int kIsPredictingKillRagdollsFieldNumber = 13;
  bool is_predicting_kill_ragdolls() const;
  void set_is_predicting_kill_ragdolls(bool value);

  // optional int32 attack3_start_history_index = 8 [default = -1];
  bool has_attack3_start_history_index() const;
  void clear_attack3_start_history_index();
  static const int kAttack3StartHistoryIndexFieldNumber = 8;
  ::google::protobuf::int32 attack3_start_history_index() const;
  void set_attack3_start_history_index(::google::protobuf::int32 value);

  // optional int32 attack1_start_history_index = 6 [default = -1];
  bool has_attack1_start_history_index() const;
  void clear_attack1_start_history_index();
  static const int kAttack1StartHistoryIndexFieldNumber = 6;
  ::google::protobuf::int32 attack1_start_history_index() const;
  void set_attack1_start_history_index(::google::protobuf::int32 value);

  // optional int32 attack2_start_history_index = 7 [default = -1];
  bool has_attack2_start_history_index() const;
  void clear_attack2_start_history_index();
  static const int kAttack2StartHistoryIndexFieldNumber = 7;
  ::google::protobuf::int32 attack2_start_history_index() const;
  void set_attack2_start_history_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CSGOUserCmdPB)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::CSGOInputHistoryEntryPB > input_history_;
  ::CBaseUserCmdPB* base_;
  bool left_hand_desired_;
  bool is_predicting_body_shot_fx_;
  bool is_predicting_head_shot_fx_;
  bool is_predicting_kill_ragdolls_;
  ::google::protobuf::int32 attack3_start_history_index_;
  ::google::protobuf::int32 attack1_start_history_index_;
  ::google::protobuf::int32 attack2_start_history_index_;
  friend struct ::TableStruct_cs_5fusercmd_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CSGOInterpolationInfoPB

// optional int32 src_tick = 1 [default = -1];
inline bool CSGOInterpolationInfoPB::has_src_tick() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CSGOInterpolationInfoPB::clear_src_tick() {
  src_tick_ = -1;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 CSGOInterpolationInfoPB::src_tick() const {
  // @@protoc_insertion_point(field_get:CSGOInterpolationInfoPB.src_tick)
  return src_tick_;
}
inline void CSGOInterpolationInfoPB::set_src_tick(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  src_tick_ = value;
  // @@protoc_insertion_point(field_set:CSGOInterpolationInfoPB.src_tick)
}

// optional int32 dst_tick = 2 [default = -1];
inline bool CSGOInterpolationInfoPB::has_dst_tick() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CSGOInterpolationInfoPB::clear_dst_tick() {
  dst_tick_ = -1;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int32 CSGOInterpolationInfoPB::dst_tick() const {
  // @@protoc_insertion_point(field_get:CSGOInterpolationInfoPB.dst_tick)
  return dst_tick_;
}
inline void CSGOInterpolationInfoPB::set_dst_tick(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  dst_tick_ = value;
  // @@protoc_insertion_point(field_set:CSGOInterpolationInfoPB.dst_tick)
}

// optional float frac = 3 [default = 0];
inline bool CSGOInterpolationInfoPB::has_frac() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSGOInterpolationInfoPB::clear_frac() {
  frac_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline float CSGOInterpolationInfoPB::frac() const {
  // @@protoc_insertion_point(field_get:CSGOInterpolationInfoPB.frac)
  return frac_;
}
inline void CSGOInterpolationInfoPB::set_frac(float value) {
  _has_bits_[0] |= 0x00000001u;
  frac_ = value;
  // @@protoc_insertion_point(field_set:CSGOInterpolationInfoPB.frac)
}

// -------------------------------------------------------------------

// CSGOInterpolationInfoPB_CL

// optional float frac = 3 [default = 0];
inline bool CSGOInterpolationInfoPB_CL::has_frac() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSGOInterpolationInfoPB_CL::clear_frac() {
  frac_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline float CSGOInterpolationInfoPB_CL::frac() const {
  // @@protoc_insertion_point(field_get:CSGOInterpolationInfoPB_CL.frac)
  return frac_;
}
inline void CSGOInterpolationInfoPB_CL::set_frac(float value) {
  _has_bits_[0] |= 0x00000001u;
  frac_ = value;
  // @@protoc_insertion_point(field_set:CSGOInterpolationInfoPB_CL.frac)
}

// -------------------------------------------------------------------

// CSGOInputHistoryEntryPB

// optional .CMsgQAngle view_angles = 2;
inline bool CSGOInputHistoryEntryPB::has_view_angles() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline const ::CMsgQAngle& CSGOInputHistoryEntryPB::view_angles() const {
  const ::CMsgQAngle* p = view_angles_;
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.view_angles)
  return p != nullptr ? *p : *reinterpret_cast<const ::CMsgQAngle*>(
      &::_CMsgQAngle_default_instance_);
}
inline ::CMsgQAngle* CSGOInputHistoryEntryPB::release_view_angles() {
  // @@protoc_insertion_point(field_release:CSGOInputHistoryEntryPB.view_angles)
  _has_bits_[0] &= ~0x00000001u;
  ::CMsgQAngle* temp = view_angles_;
  view_angles_ = nullptr;
  return temp;
}
inline ::CMsgQAngle* CSGOInputHistoryEntryPB::mutable_view_angles() {
  _has_bits_[0] |= 0x00000001u;
  if (view_angles_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMsgQAngle>(GetArenaNoVirtual());
    view_angles_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CSGOInputHistoryEntryPB.view_angles)
  return view_angles_;
}
inline void CSGOInputHistoryEntryPB::set_allocated_view_angles(::CMsgQAngle* view_angles) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(view_angles_);
  }
  if (view_angles) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      view_angles = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, view_angles, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  view_angles_ = view_angles;
  // @@protoc_insertion_point(field_set_allocated:CSGOInputHistoryEntryPB.view_angles)
}

// optional int32 render_tick_count = 4;
inline bool CSGOInputHistoryEntryPB::has_render_tick_count() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void CSGOInputHistoryEntryPB::clear_render_tick_count() {
  render_tick_count_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline ::google::protobuf::int32 CSGOInputHistoryEntryPB::render_tick_count() const {
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.render_tick_count)
  return render_tick_count_;
}
inline void CSGOInputHistoryEntryPB::set_render_tick_count(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000200u;
  render_tick_count_ = value;
  // @@protoc_insertion_point(field_set:CSGOInputHistoryEntryPB.render_tick_count)
}

// optional float render_tick_fraction = 5;
inline bool CSGOInputHistoryEntryPB::has_render_tick_fraction() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void CSGOInputHistoryEntryPB::clear_render_tick_fraction() {
  render_tick_fraction_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline float CSGOInputHistoryEntryPB::render_tick_fraction() const {
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.render_tick_fraction)
  return render_tick_fraction_;
}
inline void CSGOInputHistoryEntryPB::set_render_tick_fraction(float value) {
  _has_bits_[0] |= 0x00000400u;
  render_tick_fraction_ = value;
  // @@protoc_insertion_point(field_set:CSGOInputHistoryEntryPB.render_tick_fraction)
}

// optional int32 player_tick_count = 6;
inline bool CSGOInputHistoryEntryPB::has_player_tick_count() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void CSGOInputHistoryEntryPB::clear_player_tick_count() {
  player_tick_count_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline ::google::protobuf::int32 CSGOInputHistoryEntryPB::player_tick_count() const {
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.player_tick_count)
  return player_tick_count_;
}
inline void CSGOInputHistoryEntryPB::set_player_tick_count(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000800u;
  player_tick_count_ = value;
  // @@protoc_insertion_point(field_set:CSGOInputHistoryEntryPB.player_tick_count)
}

// optional float player_tick_fraction = 7;
inline bool CSGOInputHistoryEntryPB::has_player_tick_fraction() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void CSGOInputHistoryEntryPB::clear_player_tick_fraction() {
  player_tick_fraction_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline float CSGOInputHistoryEntryPB::player_tick_fraction() const {
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.player_tick_fraction)
  return player_tick_fraction_;
}
inline void CSGOInputHistoryEntryPB::set_player_tick_fraction(float value) {
  _has_bits_[0] |= 0x00001000u;
  player_tick_fraction_ = value;
  // @@protoc_insertion_point(field_set:CSGOInputHistoryEntryPB.player_tick_fraction)
}

// optional .CSGOInterpolationInfoPB_CL cl_interp = 12;
inline bool CSGOInputHistoryEntryPB::has_cl_interp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CSGOInputHistoryEntryPB::clear_cl_interp() {
  if (cl_interp_ != nullptr) cl_interp_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::CSGOInterpolationInfoPB_CL& CSGOInputHistoryEntryPB::cl_interp() const {
  const ::CSGOInterpolationInfoPB_CL* p = cl_interp_;
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.cl_interp)
  return p != nullptr ? *p : *reinterpret_cast<const ::CSGOInterpolationInfoPB_CL*>(
      &::_CSGOInterpolationInfoPB_CL_default_instance_);
}
inline ::CSGOInterpolationInfoPB_CL* CSGOInputHistoryEntryPB::release_cl_interp() {
  // @@protoc_insertion_point(field_release:CSGOInputHistoryEntryPB.cl_interp)
  _has_bits_[0] &= ~0x00000002u;
  ::CSGOInterpolationInfoPB_CL* temp = cl_interp_;
  cl_interp_ = nullptr;
  return temp;
}
inline ::CSGOInterpolationInfoPB_CL* CSGOInputHistoryEntryPB::mutable_cl_interp() {
  _has_bits_[0] |= 0x00000002u;
  if (cl_interp_ == nullptr) {
    auto* p = CreateMaybeMessage<::CSGOInterpolationInfoPB_CL>(GetArenaNoVirtual());
    cl_interp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CSGOInputHistoryEntryPB.cl_interp)
  return cl_interp_;
}
inline void CSGOInputHistoryEntryPB::set_allocated_cl_interp(::CSGOInterpolationInfoPB_CL* cl_interp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete cl_interp_;
  }
  if (cl_interp) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      cl_interp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, cl_interp, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  cl_interp_ = cl_interp;
  // @@protoc_insertion_point(field_set_allocated:CSGOInputHistoryEntryPB.cl_interp)
}

// optional .CSGOInterpolationInfoPB sv_interp0 = 13;
inline bool CSGOInputHistoryEntryPB::has_sv_interp0() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CSGOInputHistoryEntryPB::clear_sv_interp0() {
  if (sv_interp0_ != nullptr) sv_interp0_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::CSGOInterpolationInfoPB& CSGOInputHistoryEntryPB::sv_interp0() const {
  const ::CSGOInterpolationInfoPB* p = sv_interp0_;
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.sv_interp0)
  return p != nullptr ? *p : *reinterpret_cast<const ::CSGOInterpolationInfoPB*>(
      &::_CSGOInterpolationInfoPB_default_instance_);
}
inline ::CSGOInterpolationInfoPB* CSGOInputHistoryEntryPB::release_sv_interp0() {
  // @@protoc_insertion_point(field_release:CSGOInputHistoryEntryPB.sv_interp0)
  _has_bits_[0] &= ~0x00000004u;
  ::CSGOInterpolationInfoPB* temp = sv_interp0_;
  sv_interp0_ = nullptr;
  return temp;
}
inline ::CSGOInterpolationInfoPB* CSGOInputHistoryEntryPB::mutable_sv_interp0() {
  _has_bits_[0] |= 0x00000004u;
  if (sv_interp0_ == nullptr) {
    auto* p = CreateMaybeMessage<::CSGOInterpolationInfoPB>(GetArenaNoVirtual());
    sv_interp0_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CSGOInputHistoryEntryPB.sv_interp0)
  return sv_interp0_;
}
inline void CSGOInputHistoryEntryPB::set_allocated_sv_interp0(::CSGOInterpolationInfoPB* sv_interp0) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete sv_interp0_;
  }
  if (sv_interp0) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      sv_interp0 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, sv_interp0, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  sv_interp0_ = sv_interp0;
  // @@protoc_insertion_point(field_set_allocated:CSGOInputHistoryEntryPB.sv_interp0)
}

// optional .CSGOInterpolationInfoPB sv_interp1 = 14;
inline bool CSGOInputHistoryEntryPB::has_sv_interp1() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CSGOInputHistoryEntryPB::clear_sv_interp1() {
  if (sv_interp1_ != nullptr) sv_interp1_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::CSGOInterpolationInfoPB& CSGOInputHistoryEntryPB::sv_interp1() const {
  const ::CSGOInterpolationInfoPB* p = sv_interp1_;
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.sv_interp1)
  return p != nullptr ? *p : *reinterpret_cast<const ::CSGOInterpolationInfoPB*>(
      &::_CSGOInterpolationInfoPB_default_instance_);
}
inline ::CSGOInterpolationInfoPB* CSGOInputHistoryEntryPB::release_sv_interp1() {
  // @@protoc_insertion_point(field_release:CSGOInputHistoryEntryPB.sv_interp1)
  _has_bits_[0] &= ~0x00000008u;
  ::CSGOInterpolationInfoPB* temp = sv_interp1_;
  sv_interp1_ = nullptr;
  return temp;
}
inline ::CSGOInterpolationInfoPB* CSGOInputHistoryEntryPB::mutable_sv_interp1() {
  _has_bits_[0] |= 0x00000008u;
  if (sv_interp1_ == nullptr) {
    auto* p = CreateMaybeMessage<::CSGOInterpolationInfoPB>(GetArenaNoVirtual());
    sv_interp1_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CSGOInputHistoryEntryPB.sv_interp1)
  return sv_interp1_;
}
inline void CSGOInputHistoryEntryPB::set_allocated_sv_interp1(::CSGOInterpolationInfoPB* sv_interp1) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete sv_interp1_;
  }
  if (sv_interp1) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      sv_interp1 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, sv_interp1, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  sv_interp1_ = sv_interp1;
  // @@protoc_insertion_point(field_set_allocated:CSGOInputHistoryEntryPB.sv_interp1)
}

// optional .CSGOInterpolationInfoPB player_interp = 15;
inline bool CSGOInputHistoryEntryPB::has_player_interp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CSGOInputHistoryEntryPB::clear_player_interp() {
  if (player_interp_ != nullptr) player_interp_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
inline const ::CSGOInterpolationInfoPB& CSGOInputHistoryEntryPB::player_interp() const {
  const ::CSGOInterpolationInfoPB* p = player_interp_;
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.player_interp)
  return p != nullptr ? *p : *reinterpret_cast<const ::CSGOInterpolationInfoPB*>(
      &::_CSGOInterpolationInfoPB_default_instance_);
}
inline ::CSGOInterpolationInfoPB* CSGOInputHistoryEntryPB::release_player_interp() {
  // @@protoc_insertion_point(field_release:CSGOInputHistoryEntryPB.player_interp)
  _has_bits_[0] &= ~0x00000010u;
  ::CSGOInterpolationInfoPB* temp = player_interp_;
  player_interp_ = nullptr;
  return temp;
}
inline ::CSGOInterpolationInfoPB* CSGOInputHistoryEntryPB::mutable_player_interp() {
  _has_bits_[0] |= 0x00000010u;
  if (player_interp_ == nullptr) {
    auto* p = CreateMaybeMessage<::CSGOInterpolationInfoPB>(GetArenaNoVirtual());
    player_interp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CSGOInputHistoryEntryPB.player_interp)
  return player_interp_;
}
inline void CSGOInputHistoryEntryPB::set_allocated_player_interp(::CSGOInterpolationInfoPB* player_interp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete player_interp_;
  }
  if (player_interp) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      player_interp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, player_interp, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  player_interp_ = player_interp;
  // @@protoc_insertion_point(field_set_allocated:CSGOInputHistoryEntryPB.player_interp)
}

// optional int32 frame_number = 64;
inline bool CSGOInputHistoryEntryPB::has_frame_number() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void CSGOInputHistoryEntryPB::clear_frame_number() {
  frame_number_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline ::google::protobuf::int32 CSGOInputHistoryEntryPB::frame_number() const {
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.frame_number)
  return frame_number_;
}
inline void CSGOInputHistoryEntryPB::set_frame_number(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00002000u;
  frame_number_ = value;
  // @@protoc_insertion_point(field_set:CSGOInputHistoryEntryPB.frame_number)
}

// optional int32 target_ent_index = 65 [default = -1];
inline bool CSGOInputHistoryEntryPB::has_target_ent_index() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void CSGOInputHistoryEntryPB::clear_target_ent_index() {
  target_ent_index_ = -1;
  _has_bits_[0] &= ~0x00004000u;
}
inline ::google::protobuf::int32 CSGOInputHistoryEntryPB::target_ent_index() const {
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.target_ent_index)
  return target_ent_index_;
}
inline void CSGOInputHistoryEntryPB::set_target_ent_index(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00004000u;
  target_ent_index_ = value;
  // @@protoc_insertion_point(field_set:CSGOInputHistoryEntryPB.target_ent_index)
}

// optional .CMsgVector shoot_position = 66;
inline bool CSGOInputHistoryEntryPB::has_shoot_position() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline const ::CMsgVector& CSGOInputHistoryEntryPB::shoot_position() const {
  const ::CMsgVector* p = shoot_position_;
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.shoot_position)
  return p != nullptr ? *p : *reinterpret_cast<const ::CMsgVector*>(
      &::_CMsgVector_default_instance_);
}
inline ::CMsgVector* CSGOInputHistoryEntryPB::release_shoot_position() {
  // @@protoc_insertion_point(field_release:CSGOInputHistoryEntryPB.shoot_position)
  _has_bits_[0] &= ~0x00000020u;
  ::CMsgVector* temp = shoot_position_;
  shoot_position_ = nullptr;
  return temp;
}
inline ::CMsgVector* CSGOInputHistoryEntryPB::mutable_shoot_position() {
  _has_bits_[0] |= 0x00000020u;
  if (shoot_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMsgVector>(GetArenaNoVirtual());
    shoot_position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CSGOInputHistoryEntryPB.shoot_position)
  return shoot_position_;
}
inline void CSGOInputHistoryEntryPB::set_allocated_shoot_position(::CMsgVector* shoot_position) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(shoot_position_);
  }
  if (shoot_position) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      shoot_position = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, shoot_position, submessage_arena);
    }
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  shoot_position_ = shoot_position;
  // @@protoc_insertion_point(field_set_allocated:CSGOInputHistoryEntryPB.shoot_position)
}

// optional .CMsgVector target_head_pos_check = 67;
inline bool CSGOInputHistoryEntryPB::has_target_head_pos_check() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline const ::CMsgVector& CSGOInputHistoryEntryPB::target_head_pos_check() const {
  const ::CMsgVector* p = target_head_pos_check_;
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.target_head_pos_check)
  return p != nullptr ? *p : *reinterpret_cast<const ::CMsgVector*>(
      &::_CMsgVector_default_instance_);
}
inline ::CMsgVector* CSGOInputHistoryEntryPB::release_target_head_pos_check() {
  // @@protoc_insertion_point(field_release:CSGOInputHistoryEntryPB.target_head_pos_check)
  _has_bits_[0] &= ~0x00000040u;
  ::CMsgVector* temp = target_head_pos_check_;
  target_head_pos_check_ = nullptr;
  return temp;
}
inline ::CMsgVector* CSGOInputHistoryEntryPB::mutable_target_head_pos_check() {
  _has_bits_[0] |= 0x00000040u;
  if (target_head_pos_check_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMsgVector>(GetArenaNoVirtual());
    target_head_pos_check_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CSGOInputHistoryEntryPB.target_head_pos_check)
  return target_head_pos_check_;
}
inline void CSGOInputHistoryEntryPB::set_allocated_target_head_pos_check(::CMsgVector* target_head_pos_check) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(target_head_pos_check_);
  }
  if (target_head_pos_check) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      target_head_pos_check = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, target_head_pos_check, submessage_arena);
    }
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  target_head_pos_check_ = target_head_pos_check;
  // @@protoc_insertion_point(field_set_allocated:CSGOInputHistoryEntryPB.target_head_pos_check)
}

// optional .CMsgVector target_abs_pos_check = 68;
inline bool CSGOInputHistoryEntryPB::has_target_abs_pos_check() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline const ::CMsgVector& CSGOInputHistoryEntryPB::target_abs_pos_check() const {
  const ::CMsgVector* p = target_abs_pos_check_;
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.target_abs_pos_check)
  return p != nullptr ? *p : *reinterpret_cast<const ::CMsgVector*>(
      &::_CMsgVector_default_instance_);
}
inline ::CMsgVector* CSGOInputHistoryEntryPB::release_target_abs_pos_check() {
  // @@protoc_insertion_point(field_release:CSGOInputHistoryEntryPB.target_abs_pos_check)
  _has_bits_[0] &= ~0x00000080u;
  ::CMsgVector* temp = target_abs_pos_check_;
  target_abs_pos_check_ = nullptr;
  return temp;
}
inline ::CMsgVector* CSGOInputHistoryEntryPB::mutable_target_abs_pos_check() {
  _has_bits_[0] |= 0x00000080u;
  if (target_abs_pos_check_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMsgVector>(GetArenaNoVirtual());
    target_abs_pos_check_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CSGOInputHistoryEntryPB.target_abs_pos_check)
  return target_abs_pos_check_;
}
inline void CSGOInputHistoryEntryPB::set_allocated_target_abs_pos_check(::CMsgVector* target_abs_pos_check) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(target_abs_pos_check_);
  }
  if (target_abs_pos_check) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      target_abs_pos_check = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, target_abs_pos_check, submessage_arena);
    }
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  target_abs_pos_check_ = target_abs_pos_check;
  // @@protoc_insertion_point(field_set_allocated:CSGOInputHistoryEntryPB.target_abs_pos_check)
}

// optional .CMsgQAngle target_abs_ang_check = 69;
inline bool CSGOInputHistoryEntryPB::has_target_abs_ang_check() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline const ::CMsgQAngle& CSGOInputHistoryEntryPB::target_abs_ang_check() const {
  const ::CMsgQAngle* p = target_abs_ang_check_;
  // @@protoc_insertion_point(field_get:CSGOInputHistoryEntryPB.target_abs_ang_check)
  return p != nullptr ? *p : *reinterpret_cast<const ::CMsgQAngle*>(
      &::_CMsgQAngle_default_instance_);
}
inline ::CMsgQAngle* CSGOInputHistoryEntryPB::release_target_abs_ang_check() {
  // @@protoc_insertion_point(field_release:CSGOInputHistoryEntryPB.target_abs_ang_check)
  _has_bits_[0] &= ~0x00000100u;
  ::CMsgQAngle* temp = target_abs_ang_check_;
  target_abs_ang_check_ = nullptr;
  return temp;
}
inline ::CMsgQAngle* CSGOInputHistoryEntryPB::mutable_target_abs_ang_check() {
  _has_bits_[0] |= 0x00000100u;
  if (target_abs_ang_check_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMsgQAngle>(GetArenaNoVirtual());
    target_abs_ang_check_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CSGOInputHistoryEntryPB.target_abs_ang_check)
  return target_abs_ang_check_;
}
inline void CSGOInputHistoryEntryPB::set_allocated_target_abs_ang_check(::CMsgQAngle* target_abs_ang_check) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(target_abs_ang_check_);
  }
  if (target_abs_ang_check) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      target_abs_ang_check = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, target_abs_ang_check, submessage_arena);
    }
    _has_bits_[0] |= 0x00000100u;
  } else {
    _has_bits_[0] &= ~0x00000100u;
  }
  target_abs_ang_check_ = target_abs_ang_check;
  // @@protoc_insertion_point(field_set_allocated:CSGOInputHistoryEntryPB.target_abs_ang_check)
}

// -------------------------------------------------------------------

// CSGOUserCmdPB

// optional .CBaseUserCmdPB base = 1;
inline bool CSGOUserCmdPB::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline const ::CBaseUserCmdPB& CSGOUserCmdPB::base() const {
  const ::CBaseUserCmdPB* p = base_;
  // @@protoc_insertion_point(field_get:CSGOUserCmdPB.base)
  return p != nullptr ? *p : *reinterpret_cast<const ::CBaseUserCmdPB*>(
      &::_CBaseUserCmdPB_default_instance_);
}
inline ::CBaseUserCmdPB* CSGOUserCmdPB::release_base() {
  // @@protoc_insertion_point(field_release:CSGOUserCmdPB.base)
  _has_bits_[0] &= ~0x00000001u;
  ::CBaseUserCmdPB* temp = base_;
  base_ = nullptr;
  return temp;
}
inline ::CBaseUserCmdPB* CSGOUserCmdPB::mutable_base() {
  _has_bits_[0] |= 0x00000001u;
  if (base_ == nullptr) {
    auto* p = CreateMaybeMessage<::CBaseUserCmdPB>(GetArenaNoVirtual());
    base_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CSGOUserCmdPB.base)
  return base_;
}
inline void CSGOUserCmdPB::set_allocated_base(::CBaseUserCmdPB* base) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(base_);
  }
  if (base) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      base = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, base, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  base_ = base;
  // @@protoc_insertion_point(field_set_allocated:CSGOUserCmdPB.base)
}

// repeated .CSGOInputHistoryEntryPB input_history = 2;
inline int CSGOUserCmdPB::input_history_size() const {
  return input_history_.size();
}
inline void CSGOUserCmdPB::clear_input_history() {
  input_history_.Clear();
}
inline ::CSGOInputHistoryEntryPB* CSGOUserCmdPB::mutable_input_history(int index) {
  // @@protoc_insertion_point(field_mutable:CSGOUserCmdPB.input_history)
  return input_history_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::CSGOInputHistoryEntryPB >*
CSGOUserCmdPB::mutable_input_history() {
  // @@protoc_insertion_point(field_mutable_list:CSGOUserCmdPB.input_history)
  return &input_history_;
}
inline const ::CSGOInputHistoryEntryPB& CSGOUserCmdPB::input_history(int index) const {
  // @@protoc_insertion_point(field_get:CSGOUserCmdPB.input_history)
  return input_history_.Get(index);
}
inline ::CSGOInputHistoryEntryPB* CSGOUserCmdPB::add_input_history() {
  // @@protoc_insertion_point(field_add:CSGOUserCmdPB.input_history)
  return input_history_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CSGOInputHistoryEntryPB >&
CSGOUserCmdPB::input_history() const {
  // @@protoc_insertion_point(field_list:CSGOUserCmdPB.input_history)
  return input_history_;
}

// optional int32 attack1_start_history_index = 6 [default = -1];
inline bool CSGOUserCmdPB::has_attack1_start_history_index() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CSGOUserCmdPB::clear_attack1_start_history_index() {
  attack1_start_history_index_ = -1;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::google::protobuf::int32 CSGOUserCmdPB::attack1_start_history_index() const {
  // @@protoc_insertion_point(field_get:CSGOUserCmdPB.attack1_start_history_index)
  return attack1_start_history_index_;
}
inline void CSGOUserCmdPB::set_attack1_start_history_index(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000040u;
  attack1_start_history_index_ = value;
  // @@protoc_insertion_point(field_set:CSGOUserCmdPB.attack1_start_history_index)
}

// optional int32 attack2_start_history_index = 7 [default = -1];
inline bool CSGOUserCmdPB::has_attack2_start_history_index() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void CSGOUserCmdPB::clear_attack2_start_history_index() {
  attack2_start_history_index_ = -1;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::google::protobuf::int32 CSGOUserCmdPB::attack2_start_history_index() const {
  // @@protoc_insertion_point(field_get:CSGOUserCmdPB.attack2_start_history_index)
  return attack2_start_history_index_;
}
inline void CSGOUserCmdPB::set_attack2_start_history_index(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000080u;
  attack2_start_history_index_ = value;
  // @@protoc_insertion_point(field_set:CSGOUserCmdPB.attack2_start_history_index)
}

// optional int32 attack3_start_history_index = 8 [default = -1];
inline bool CSGOUserCmdPB::has_attack3_start_history_index() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CSGOUserCmdPB::clear_attack3_start_history_index() {
  attack3_start_history_index_ = -1;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::google::protobuf::int32 CSGOUserCmdPB::attack3_start_history_index() const {
  // @@protoc_insertion_point(field_get:CSGOUserCmdPB.attack3_start_history_index)
  return attack3_start_history_index_;
}
inline void CSGOUserCmdPB::set_attack3_start_history_index(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000020u;
  attack3_start_history_index_ = value;
  // @@protoc_insertion_point(field_set:CSGOUserCmdPB.attack3_start_history_index)
}

// optional bool left_hand_desired = 9 [default = false];
inline bool CSGOUserCmdPB::has_left_hand_desired() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CSGOUserCmdPB::clear_left_hand_desired() {
  left_hand_desired_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool CSGOUserCmdPB::left_hand_desired() const {
  // @@protoc_insertion_point(field_get:CSGOUserCmdPB.left_hand_desired)
  return left_hand_desired_;
}
inline void CSGOUserCmdPB::set_left_hand_desired(bool value) {
  _has_bits_[0] |= 0x00000002u;
  left_hand_desired_ = value;
  // @@protoc_insertion_point(field_set:CSGOUserCmdPB.left_hand_desired)
}

// optional bool is_predicting_body_shot_fx = 11 [default = false];
inline bool CSGOUserCmdPB::has_is_predicting_body_shot_fx() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CSGOUserCmdPB::clear_is_predicting_body_shot_fx() {
  is_predicting_body_shot_fx_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool CSGOUserCmdPB::is_predicting_body_shot_fx() const {
  // @@protoc_insertion_point(field_get:CSGOUserCmdPB.is_predicting_body_shot_fx)
  return is_predicting_body_shot_fx_;
}
inline void CSGOUserCmdPB::set_is_predicting_body_shot_fx(bool value) {
  _has_bits_[0] |= 0x00000004u;
  is_predicting_body_shot_fx_ = value;
  // @@protoc_insertion_point(field_set:CSGOUserCmdPB.is_predicting_body_shot_fx)
}

// optional bool is_predicting_head_shot_fx = 12 [default = false];
inline bool CSGOUserCmdPB::has_is_predicting_head_shot_fx() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CSGOUserCmdPB::clear_is_predicting_head_shot_fx() {
  is_predicting_head_shot_fx_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool CSGOUserCmdPB::is_predicting_head_shot_fx() const {
  // @@protoc_insertion_point(field_get:CSGOUserCmdPB.is_predicting_head_shot_fx)
  return is_predicting_head_shot_fx_;
}
inline void CSGOUserCmdPB::set_is_predicting_head_shot_fx(bool value) {
  _has_bits_[0] |= 0x00000008u;
  is_predicting_head_shot_fx_ = value;
  // @@protoc_insertion_point(field_set:CSGOUserCmdPB.is_predicting_head_shot_fx)
}

// optional bool is_predicting_kill_ragdolls = 13 [default = false];
inline bool CSGOUserCmdPB::has_is_predicting_kill_ragdolls() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CSGOUserCmdPB::clear_is_predicting_kill_ragdolls() {
  is_predicting_kill_ragdolls_ = false;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool CSGOUserCmdPB::is_predicting_kill_ragdolls() const {
  // @@protoc_insertion_point(field_get:CSGOUserCmdPB.is_predicting_kill_ragdolls)
  return is_predicting_kill_ragdolls_;
}
inline void CSGOUserCmdPB::set_is_predicting_kill_ragdolls(bool value) {
  _has_bits_[0] |= 0x00000010u;
  is_predicting_kill_ragdolls_ = value;
  // @@protoc_insertion_point(field_set:CSGOUserCmdPB.is_predicting_kill_ragdolls)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_cs_5fusercmd_2eproto
