// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usercmd.proto

#include "usercmd.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_networkbasetypes_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CMsgQAngle_networkbasetypes_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_usercmd_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CInButtonStatePB_usercmd_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_usercmd_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CSubtickMoveStep_usercmd_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_usercmd_2eproto ::google::protobuf::internal::SCCInfo<3> scc_info_CBaseUserCmdPB_usercmd_2eproto;
class CInButtonStatePBDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CInButtonStatePB> _instance;
} _CInButtonStatePB_default_instance_;
class CSubtickMoveStepDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CSubtickMoveStep> _instance;
} _CSubtickMoveStep_default_instance_;
class CBaseUserCmdPBDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CBaseUserCmdPB> _instance;
} _CBaseUserCmdPB_default_instance_;
class CUserCmdBasePBDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CUserCmdBasePB> _instance;
} _CUserCmdBasePB_default_instance_;
static void InitDefaultsCInButtonStatePB_usercmd_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CInButtonStatePB_default_instance_;
    new (ptr) ::CInButtonStatePB();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CInButtonStatePB::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CInButtonStatePB_usercmd_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCInButtonStatePB_usercmd_2eproto}, {}};

static void InitDefaultsCSubtickMoveStep_usercmd_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CSubtickMoveStep_default_instance_;
    new (ptr) ::CSubtickMoveStep();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CSubtickMoveStep::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CSubtickMoveStep_usercmd_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCSubtickMoveStep_usercmd_2eproto}, {}};

static void InitDefaultsCBaseUserCmdPB_usercmd_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CBaseUserCmdPB_default_instance_;
    new (ptr) ::CBaseUserCmdPB();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CBaseUserCmdPB::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_CBaseUserCmdPB_usercmd_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsCBaseUserCmdPB_usercmd_2eproto}, {
      &scc_info_CInButtonStatePB_usercmd_2eproto.base,
      &scc_info_CMsgQAngle_networkbasetypes_2eproto.base,
      &scc_info_CSubtickMoveStep_usercmd_2eproto.base,}};

static void InitDefaultsCUserCmdBasePB_usercmd_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CUserCmdBasePB_default_instance_;
    new (ptr) ::CUserCmdBasePB();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CUserCmdBasePB::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_CUserCmdBasePB_usercmd_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsCUserCmdBasePB_usercmd_2eproto}, {
      &scc_info_CBaseUserCmdPB_usercmd_2eproto.base,}};

void InitDefaults_usercmd_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_CInButtonStatePB_usercmd_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CSubtickMoveStep_usercmd_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CBaseUserCmdPB_usercmd_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CUserCmdBasePB_usercmd_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_usercmd_2eproto[4];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_usercmd_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_usercmd_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_usercmd_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, buttonstate1_),
  PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, buttonstate2_),
  PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, buttonstate3_),
  0,
  1,
  2,
  PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, button_),
  PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, pressed_),
  PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, when_),
  PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, analog_forward_delta_),
  PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, analog_left_delta_),
  0,
  1,
  2,
  3,
  4,
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, legacy_command_number_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, client_tick_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, buttons_pb_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, viewangles_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, forwardmove_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, leftmove_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, upmove_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, impulse_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, weaponselect_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, random_seed_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, mousedx_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, mousedy_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, pawn_entity_handle_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, subtick_moves_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, move_crc_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, consumed_server_angle_changes_),
  PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, cmd_flags_),
  3,
  4,
  1,
  2,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  15,
  ~0u,
  0,
  13,
  14,
  PROTOBUF_FIELD_OFFSET(::CUserCmdBasePB, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::CUserCmdBasePB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::CUserCmdBasePB, base_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::CInButtonStatePB)},
  { 11, 21, sizeof(::CSubtickMoveStep)},
  { 26, 48, sizeof(::CBaseUserCmdPB)},
  { 65, 71, sizeof(::CUserCmdBasePB)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CInButtonStatePB_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CSubtickMoveStep_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CBaseUserCmdPB_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CUserCmdBasePB_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_usercmd_2eproto = {
  {}, AddDescriptors_usercmd_2eproto, "usercmd.proto", schemas,
  file_default_instances, TableStruct_usercmd_2eproto::offsets,
  file_level_metadata_usercmd_2eproto, 4, file_level_enum_descriptors_usercmd_2eproto, file_level_service_descriptors_usercmd_2eproto,
};

const char descriptor_table_protodef_usercmd_2eproto[] =
  "\n\rusercmd.proto\032\026networkbasetypes.proto\""
  "T\n\020CInButtonStatePB\022\024\n\014buttonstate1\030\001 \001("
  "\004\022\024\n\014buttonstate2\030\002 \001(\004\022\024\n\014buttonstate3\030"
  "\003 \001(\004\"z\n\020CSubtickMoveStep\022\016\n\006button\030\001 \001("
  "\004\022\017\n\007pressed\030\002 \001(\010\022\014\n\004when\030\003 \001(\002\022\034\n\024anal"
  "og_forward_delta\030\004 \001(\002\022\031\n\021analog_left_de"
  "lta\030\005 \001(\002\"\275\003\n\016CBaseUserCmdPB\022\035\n\025legacy_c"
  "ommand_number\030\001 \001(\005\022\023\n\013client_tick\030\002 \001(\005"
  "\022%\n\nbuttons_pb\030\003 \001(\0132\021.CInButtonStatePB\022"
  "\037\n\nviewangles\030\004 \001(\0132\013.CMsgQAngle\022\023\n\013forw"
  "ardmove\030\005 \001(\002\022\020\n\010leftmove\030\006 \001(\002\022\016\n\006upmov"
  "e\030\007 \001(\002\022\017\n\007impulse\030\010 \001(\005\022\024\n\014weaponselect"
  "\030\t \001(\005\022\023\n\013random_seed\030\n \001(\005\022\017\n\007mousedx\030\013"
  " \001(\005\022\017\n\007mousedy\030\014 \001(\005\022$\n\022pawn_entity_han"
  "dle\030\016 \001(\r:\01016777215\022(\n\rsubtick_moves\030\022 \003"
  "(\0132\021.CSubtickMoveStep\022\020\n\010move_crc\030\023 \001(\014\022"
  "%\n\035consumed_server_angle_changes\030\024 \001(\r\022\021"
  "\n\tcmd_flags\030\025 \001(\005\"/\n\016CUserCmdBasePB\022\035\n\004b"
  "ase\030\001 \001(\0132\017.CBaseUserCmdPB"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_usercmd_2eproto = {
  false, InitDefaults_usercmd_2eproto, 
  descriptor_table_protodef_usercmd_2eproto,
  "usercmd.proto", &assign_descriptors_table_usercmd_2eproto, 746,
};

void AddDescriptors_usercmd_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_networkbasetypes_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_usercmd_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_usercmd_2eproto = []() { AddDescriptors_usercmd_2eproto(); return true; }();

// ===================================================================

void CInButtonStatePB::InitAsDefaultInstance() {
}
class CInButtonStatePB::HasBitSetters {
 public:
  static void set_has_buttonstate1(CInButtonStatePB* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
  static void set_has_buttonstate2(CInButtonStatePB* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static void set_has_buttonstate3(CInButtonStatePB* msg) {
    msg->_has_bits_[0] |= 0x00000004u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CInButtonStatePB::kButtonstate1FieldNumber;
const int CInButtonStatePB::kButtonstate2FieldNumber;
const int CInButtonStatePB::kButtonstate3FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CInButtonStatePB::CInButtonStatePB()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CInButtonStatePB)
}
CInButtonStatePB::CInButtonStatePB(const CInButtonStatePB& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&buttonstate1_, &from.buttonstate1_,
    static_cast<size_t>(reinterpret_cast<char*>(&buttonstate3_) -
    reinterpret_cast<char*>(&buttonstate1_)) + sizeof(buttonstate3_));
  // @@protoc_insertion_point(copy_constructor:CInButtonStatePB)
}

void CInButtonStatePB::SharedCtor() {
  ::memset(&buttonstate1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&buttonstate3_) -
      reinterpret_cast<char*>(&buttonstate1_)) + sizeof(buttonstate3_));
}

CInButtonStatePB::~CInButtonStatePB() {
  // @@protoc_insertion_point(destructor:CInButtonStatePB)
  SharedDtor();
}

void CInButtonStatePB::SharedDtor() {
}

void CInButtonStatePB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CInButtonStatePB& CInButtonStatePB::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_CInButtonStatePB_usercmd_2eproto.base);
  return *internal_default_instance();
}


void CInButtonStatePB::Clear() {
// @@protoc_insertion_point(message_clear_start:CInButtonStatePB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&buttonstate1_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&buttonstate3_) -
        reinterpret_cast<char*>(&buttonstate1_)) + sizeof(buttonstate3_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* CInButtonStatePB::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<CInButtonStatePB*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional uint64 buttonstate1 = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_buttonstate1(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional uint64 buttonstate2 = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_buttonstate2(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional uint64 buttonstate3 = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        msg->set_buttonstate3(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool CInButtonStatePB::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CInButtonStatePB)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 buttonstate1 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_buttonstate1(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &buttonstate1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint64 buttonstate2 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          HasBitSetters::set_has_buttonstate2(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &buttonstate2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint64 buttonstate3 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {
          HasBitSetters::set_has_buttonstate3(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &buttonstate3_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CInButtonStatePB)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CInButtonStatePB)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void CInButtonStatePB::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CInButtonStatePB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 buttonstate1 = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->buttonstate1(), output);
  }

  // optional uint64 buttonstate2 = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->buttonstate2(), output);
  }

  // optional uint64 buttonstate3 = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->buttonstate3(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CInButtonStatePB)
}

::google::protobuf::uint8* CInButtonStatePB::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CInButtonStatePB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 buttonstate1 = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->buttonstate1(), target);
  }

  // optional uint64 buttonstate2 = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->buttonstate2(), target);
  }

  // optional uint64 buttonstate3 = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->buttonstate3(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CInButtonStatePB)
  return target;
}

size_t CInButtonStatePB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CInButtonStatePB)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional uint64 buttonstate1 = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->buttonstate1());
    }

    // optional uint64 buttonstate2 = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->buttonstate2());
    }

    // optional uint64 buttonstate3 = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->buttonstate3());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CInButtonStatePB::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CInButtonStatePB)
  GOOGLE_DCHECK_NE(&from, this);
  const CInButtonStatePB* source =
      ::google::protobuf::DynamicCastToGenerated<CInButtonStatePB>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CInButtonStatePB)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CInButtonStatePB)
    MergeFrom(*source);
  }
}

void CInButtonStatePB::MergeFrom(const CInButtonStatePB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CInButtonStatePB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      buttonstate1_ = from.buttonstate1_;
    }
    if (cached_has_bits & 0x00000002u) {
      buttonstate2_ = from.buttonstate2_;
    }
    if (cached_has_bits & 0x00000004u) {
      buttonstate3_ = from.buttonstate3_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CInButtonStatePB::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CInButtonStatePB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CInButtonStatePB::CopyFrom(const CInButtonStatePB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CInButtonStatePB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CInButtonStatePB::IsInitialized() const {
  return true;
}

void CInButtonStatePB::Swap(CInButtonStatePB* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CInButtonStatePB::InternalSwap(CInButtonStatePB* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(buttonstate1_, other->buttonstate1_);
  swap(buttonstate2_, other->buttonstate2_);
  swap(buttonstate3_, other->buttonstate3_);
}

::google::protobuf::Metadata CInButtonStatePB::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_usercmd_2eproto);
  return ::file_level_metadata_usercmd_2eproto[kIndexInFileMessages];
}


// ===================================================================

void CSubtickMoveStep::InitAsDefaultInstance() {
}
class CSubtickMoveStep::HasBitSetters {
 public:
  static void set_has_button(CSubtickMoveStep* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
  static void set_has_pressed(CSubtickMoveStep* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static void set_has_when(CSubtickMoveStep* msg) {
    msg->_has_bits_[0] |= 0x00000004u;
  }
  static void set_has_analog_forward_delta(CSubtickMoveStep* msg) {
    msg->_has_bits_[0] |= 0x00000008u;
  }
  static void set_has_analog_left_delta(CSubtickMoveStep* msg) {
    msg->_has_bits_[0] |= 0x00000010u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CSubtickMoveStep::kButtonFieldNumber;
const int CSubtickMoveStep::kPressedFieldNumber;
const int CSubtickMoveStep::kWhenFieldNumber;
const int CSubtickMoveStep::kAnalogForwardDeltaFieldNumber;
const int CSubtickMoveStep::kAnalogLeftDeltaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CSubtickMoveStep::CSubtickMoveStep()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CSubtickMoveStep)
}
CSubtickMoveStep::CSubtickMoveStep(const CSubtickMoveStep& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&button_, &from.button_,
    static_cast<size_t>(reinterpret_cast<char*>(&analog_left_delta_) -
    reinterpret_cast<char*>(&button_)) + sizeof(analog_left_delta_));
  // @@protoc_insertion_point(copy_constructor:CSubtickMoveStep)
}

void CSubtickMoveStep::SharedCtor() {
  ::memset(&button_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&analog_left_delta_) -
      reinterpret_cast<char*>(&button_)) + sizeof(analog_left_delta_));
}

CSubtickMoveStep::~CSubtickMoveStep() {
  // @@protoc_insertion_point(destructor:CSubtickMoveStep)
  SharedDtor();
}

void CSubtickMoveStep::SharedDtor() {
}

void CSubtickMoveStep::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CSubtickMoveStep& CSubtickMoveStep::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_CSubtickMoveStep_usercmd_2eproto.base);
  return *internal_default_instance();
}


void CSubtickMoveStep::Clear() {
// @@protoc_insertion_point(message_clear_start:CSubtickMoveStep)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    ::memset(&button_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&analog_left_delta_) -
        reinterpret_cast<char*>(&button_)) + sizeof(analog_left_delta_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* CSubtickMoveStep::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<CSubtickMoveStep*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional uint64 button = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_button(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional bool pressed = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_pressed(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional float when = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 29) goto handle_unusual;
        msg->set_when(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // optional float analog_forward_delta = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 37) goto handle_unusual;
        msg->set_analog_forward_delta(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // optional float analog_left_delta = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 45) goto handle_unusual;
        msg->set_analog_left_delta(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool CSubtickMoveStep::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CSubtickMoveStep)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 button = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_button(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &button_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool pressed = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          HasBitSetters::set_has_pressed(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &pressed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float when = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (29 & 0xFF)) {
          HasBitSetters::set_has_when(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &when_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float analog_forward_delta = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (37 & 0xFF)) {
          HasBitSetters::set_has_analog_forward_delta(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &analog_forward_delta_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float analog_left_delta = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (45 & 0xFF)) {
          HasBitSetters::set_has_analog_left_delta(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &analog_left_delta_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CSubtickMoveStep)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CSubtickMoveStep)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void CSubtickMoveStep::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CSubtickMoveStep)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 button = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->button(), output);
  }

  // optional bool pressed = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->pressed(), output);
  }

  // optional float when = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->when(), output);
  }

  // optional float analog_forward_delta = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->analog_forward_delta(), output);
  }

  // optional float analog_left_delta = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->analog_left_delta(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CSubtickMoveStep)
}

::google::protobuf::uint8* CSubtickMoveStep::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSubtickMoveStep)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 button = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->button(), target);
  }

  // optional bool pressed = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->pressed(), target);
  }

  // optional float when = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->when(), target);
  }

  // optional float analog_forward_delta = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->analog_forward_delta(), target);
  }

  // optional float analog_left_delta = 5;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->analog_left_delta(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CSubtickMoveStep)
  return target;
}

size_t CSubtickMoveStep::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CSubtickMoveStep)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional uint64 button = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->button());
    }

    // optional bool pressed = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional float when = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 4;
    }

    // optional float analog_forward_delta = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 4;
    }

    // optional float analog_left_delta = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 4;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CSubtickMoveStep::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CSubtickMoveStep)
  GOOGLE_DCHECK_NE(&from, this);
  const CSubtickMoveStep* source =
      ::google::protobuf::DynamicCastToGenerated<CSubtickMoveStep>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CSubtickMoveStep)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CSubtickMoveStep)
    MergeFrom(*source);
  }
}

void CSubtickMoveStep::MergeFrom(const CSubtickMoveStep& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CSubtickMoveStep)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      button_ = from.button_;
    }
    if (cached_has_bits & 0x00000002u) {
      pressed_ = from.pressed_;
    }
    if (cached_has_bits & 0x00000004u) {
      when_ = from.when_;
    }
    if (cached_has_bits & 0x00000008u) {
      analog_forward_delta_ = from.analog_forward_delta_;
    }
    if (cached_has_bits & 0x00000010u) {
      analog_left_delta_ = from.analog_left_delta_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CSubtickMoveStep::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CSubtickMoveStep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSubtickMoveStep::CopyFrom(const CSubtickMoveStep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSubtickMoveStep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSubtickMoveStep::IsInitialized() const {
  return true;
}

void CSubtickMoveStep::Swap(CSubtickMoveStep* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CSubtickMoveStep::InternalSwap(CSubtickMoveStep* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(button_, other->button_);
  swap(pressed_, other->pressed_);
  swap(when_, other->when_);
  swap(analog_forward_delta_, other->analog_forward_delta_);
  swap(analog_left_delta_, other->analog_left_delta_);
}

::google::protobuf::Metadata CSubtickMoveStep::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_usercmd_2eproto);
  return ::file_level_metadata_usercmd_2eproto[kIndexInFileMessages];
}


// ===================================================================

void CBaseUserCmdPB::InitAsDefaultInstance() {
  ::_CBaseUserCmdPB_default_instance_._instance.get_mutable()->buttons_pb_ = const_cast< ::CInButtonStatePB*>(
      ::CInButtonStatePB::internal_default_instance());
  ::_CBaseUserCmdPB_default_instance_._instance.get_mutable()->viewangles_ = const_cast< ::CMsgQAngle*>(
      ::CMsgQAngle::internal_default_instance());
}
class CBaseUserCmdPB::HasBitSetters {
 public:
  static void set_has_legacy_command_number(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000008u;
  }
  static void set_has_client_tick(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000010u;
  }
  static const ::CInButtonStatePB& buttons_pb(const CBaseUserCmdPB* msg);
  static void set_has_buttons_pb(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static const ::CMsgQAngle& viewangles(const CBaseUserCmdPB* msg);
  static void set_has_viewangles(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000004u;
  }
  static void set_has_forwardmove(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000020u;
  }
  static void set_has_leftmove(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000040u;
  }
  static void set_has_upmove(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000080u;
  }
  static void set_has_impulse(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000100u;
  }
  static void set_has_weaponselect(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000200u;
  }
  static void set_has_random_seed(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000400u;
  }
  static void set_has_mousedx(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000800u;
  }
  static void set_has_mousedy(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00001000u;
  }
  static void set_has_pawn_entity_handle(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00008000u;
  }
  static void set_has_move_crc(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
  static void set_has_consumed_server_angle_changes(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00002000u;
  }
  static void set_has_cmd_flags(CBaseUserCmdPB* msg) {
    msg->_has_bits_[0] |= 0x00004000u;
  }
};

const ::CInButtonStatePB&
CBaseUserCmdPB::HasBitSetters::buttons_pb(const CBaseUserCmdPB* msg) {
  return *msg->buttons_pb_;
}
const ::CMsgQAngle&
CBaseUserCmdPB::HasBitSetters::viewangles(const CBaseUserCmdPB* msg) {
  return *msg->viewangles_;
}
void CBaseUserCmdPB::clear_viewangles() {
  if (viewangles_ != nullptr) viewangles_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CBaseUserCmdPB::kLegacyCommandNumberFieldNumber;
const int CBaseUserCmdPB::kClientTickFieldNumber;
const int CBaseUserCmdPB::kButtonsPbFieldNumber;
const int CBaseUserCmdPB::kViewanglesFieldNumber;
const int CBaseUserCmdPB::kForwardmoveFieldNumber;
const int CBaseUserCmdPB::kLeftmoveFieldNumber;
const int CBaseUserCmdPB::kUpmoveFieldNumber;
const int CBaseUserCmdPB::kImpulseFieldNumber;
const int CBaseUserCmdPB::kWeaponselectFieldNumber;
const int CBaseUserCmdPB::kRandomSeedFieldNumber;
const int CBaseUserCmdPB::kMousedxFieldNumber;
const int CBaseUserCmdPB::kMousedyFieldNumber;
const int CBaseUserCmdPB::kPawnEntityHandleFieldNumber;
const int CBaseUserCmdPB::kSubtickMovesFieldNumber;
const int CBaseUserCmdPB::kMoveCrcFieldNumber;
const int CBaseUserCmdPB::kConsumedServerAngleChangesFieldNumber;
const int CBaseUserCmdPB::kCmdFlagsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CBaseUserCmdPB::CBaseUserCmdPB()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CBaseUserCmdPB)
}
CBaseUserCmdPB::CBaseUserCmdPB(const CBaseUserCmdPB& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      subtick_moves_(from.subtick_moves_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  move_crc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_move_crc()) {
    move_crc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.move_crc_);
  }
  if (from.has_buttons_pb()) {
    buttons_pb_ = new ::CInButtonStatePB(*from.buttons_pb_);
  } else {
    buttons_pb_ = nullptr;
  }
  if (from.has_viewangles()) {
    viewangles_ = new ::CMsgQAngle(*from.viewangles_);
  } else {
    viewangles_ = nullptr;
  }
  ::memcpy(&legacy_command_number_, &from.legacy_command_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&pawn_entity_handle_) -
    reinterpret_cast<char*>(&legacy_command_number_)) + sizeof(pawn_entity_handle_));
  // @@protoc_insertion_point(copy_constructor:CBaseUserCmdPB)
}

void CBaseUserCmdPB::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_CBaseUserCmdPB_usercmd_2eproto.base);
  move_crc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&buttons_pb_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cmd_flags_) -
      reinterpret_cast<char*>(&buttons_pb_)) + sizeof(cmd_flags_));
  pawn_entity_handle_ = 16777215u;
}

CBaseUserCmdPB::~CBaseUserCmdPB() {
  // @@protoc_insertion_point(destructor:CBaseUserCmdPB)
  SharedDtor();
}

void CBaseUserCmdPB::SharedDtor() {
  move_crc_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete buttons_pb_;
  if (this != internal_default_instance()) delete viewangles_;
}

void CBaseUserCmdPB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CBaseUserCmdPB& CBaseUserCmdPB::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_CBaseUserCmdPB_usercmd_2eproto.base);
  return *internal_default_instance();
}


void CBaseUserCmdPB::Clear() {
// @@protoc_insertion_point(message_clear_start:CBaseUserCmdPB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  subtick_moves_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      move_crc_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(buttons_pb_ != nullptr);
      buttons_pb_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(viewangles_ != nullptr);
      viewangles_->Clear();
    }
  }
  if (cached_has_bits & 0x000000f8u) {
    ::memset(&legacy_command_number_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&upmove_) -
        reinterpret_cast<char*>(&legacy_command_number_)) + sizeof(upmove_));
  }
  if (cached_has_bits & 0x0000ff00u) {
    ::memset(&impulse_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&cmd_flags_) -
        reinterpret_cast<char*>(&impulse_)) + sizeof(cmd_flags_));
    pawn_entity_handle_ = 16777215u;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* CBaseUserCmdPB::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<CBaseUserCmdPB*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional int32 legacy_command_number = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_legacy_command_number(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional int32 client_tick = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_client_tick(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional .CInButtonStatePB buttons_pb = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::CInButtonStatePB::_InternalParse;
        object = msg->mutable_buttons_pb();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // optional .CMsgQAngle viewangles = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::CMsgQAngle::_InternalParse;
        object = msg->mutable_viewangles();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // optional float forwardmove = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 45) goto handle_unusual;
        msg->set_forwardmove(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // optional float leftmove = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 53) goto handle_unusual;
        msg->set_leftmove(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // optional float upmove = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 61) goto handle_unusual;
        msg->set_upmove(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // optional int32 impulse = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 64) goto handle_unusual;
        msg->set_impulse(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional int32 weaponselect = 9;
      case 9: {
        if (static_cast<::google::protobuf::uint8>(tag) != 72) goto handle_unusual;
        msg->set_weaponselect(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional int32 random_seed = 10;
      case 10: {
        if (static_cast<::google::protobuf::uint8>(tag) != 80) goto handle_unusual;
        msg->set_random_seed(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional int32 mousedx = 11;
      case 11: {
        if (static_cast<::google::protobuf::uint8>(tag) != 88) goto handle_unusual;
        msg->set_mousedx(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional int32 mousedy = 12;
      case 12: {
        if (static_cast<::google::protobuf::uint8>(tag) != 96) goto handle_unusual;
        msg->set_mousedy(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional uint32 pawn_entity_handle = 14 [default = 16777215];
      case 14: {
        if (static_cast<::google::protobuf::uint8>(tag) != 112) goto handle_unusual;
        msg->set_pawn_entity_handle(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // repeated .CSubtickMoveStep subtick_moves = 18;
      case 18: {
        if (static_cast<::google::protobuf::uint8>(tag) != 146) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::CSubtickMoveStep::_InternalParse;
          object = msg->add_subtick_moves();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 65535) == 402 && (ptr += 2));
        break;
      }
      // optional bytes move_crc = 19;
      case 19: {
        if (static_cast<::google::protobuf::uint8>(tag) != 154) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_move_crc();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // optional uint32 consumed_server_angle_changes = 20;
      case 20: {
        if (static_cast<::google::protobuf::uint8>(tag) != 160) goto handle_unusual;
        msg->set_consumed_server_angle_changes(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional int32 cmd_flags = 21;
      case 21: {
        if (static_cast<::google::protobuf::uint8>(tag) != 168) goto handle_unusual;
        msg->set_cmd_flags(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool CBaseUserCmdPB::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CBaseUserCmdPB)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 legacy_command_number = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_legacy_command_number(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &legacy_command_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 client_tick = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          HasBitSetters::set_has_client_tick(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &client_tick_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .CInButtonStatePB buttons_pb = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_buttons_pb()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .CMsgQAngle viewangles = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_viewangles()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float forwardmove = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (45 & 0xFF)) {
          HasBitSetters::set_has_forwardmove(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &forwardmove_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float leftmove = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (53 & 0xFF)) {
          HasBitSetters::set_has_leftmove(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &leftmove_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float upmove = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (61 & 0xFF)) {
          HasBitSetters::set_has_upmove(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &upmove_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 impulse = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (64 & 0xFF)) {
          HasBitSetters::set_has_impulse(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &impulse_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 weaponselect = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (72 & 0xFF)) {
          HasBitSetters::set_has_weaponselect(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &weaponselect_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 random_seed = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (80 & 0xFF)) {
          HasBitSetters::set_has_random_seed(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &random_seed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 mousedx = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (88 & 0xFF)) {
          HasBitSetters::set_has_mousedx(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mousedx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 mousedy = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (96 & 0xFF)) {
          HasBitSetters::set_has_mousedy(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mousedy_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 pawn_entity_handle = 14 [default = 16777215];
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (112 & 0xFF)) {
          HasBitSetters::set_has_pawn_entity_handle(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &pawn_entity_handle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .CSubtickMoveStep subtick_moves = 18;
      case 18: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (146 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_subtick_moves()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes move_crc = 19;
      case 19: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (154 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_move_crc()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 consumed_server_angle_changes = 20;
      case 20: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (160 & 0xFF)) {
          HasBitSetters::set_has_consumed_server_angle_changes(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &consumed_server_angle_changes_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 cmd_flags = 21;
      case 21: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (168 & 0xFF)) {
          HasBitSetters::set_has_cmd_flags(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cmd_flags_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CBaseUserCmdPB)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CBaseUserCmdPB)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void CBaseUserCmdPB::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CBaseUserCmdPB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 legacy_command_number = 1;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->legacy_command_number(), output);
  }

  // optional int32 client_tick = 2;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->client_tick(), output);
  }

  // optional .CInButtonStatePB buttons_pb = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::buttons_pb(this), output);
  }

  // optional .CMsgQAngle viewangles = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, HasBitSetters::viewangles(this), output);
  }

  // optional float forwardmove = 5;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->forwardmove(), output);
  }

  // optional float leftmove = 6;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->leftmove(), output);
  }

  // optional float upmove = 7;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->upmove(), output);
  }

  // optional int32 impulse = 8;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->impulse(), output);
  }

  // optional int32 weaponselect = 9;
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->weaponselect(), output);
  }

  // optional int32 random_seed = 10;
  if (cached_has_bits & 0x00000400u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(10, this->random_seed(), output);
  }

  // optional int32 mousedx = 11;
  if (cached_has_bits & 0x00000800u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(11, this->mousedx(), output);
  }

  // optional int32 mousedy = 12;
  if (cached_has_bits & 0x00001000u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(12, this->mousedy(), output);
  }

  // optional uint32 pawn_entity_handle = 14 [default = 16777215];
  if (cached_has_bits & 0x00008000u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(14, this->pawn_entity_handle(), output);
  }

  // repeated .CSubtickMoveStep subtick_moves = 18;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->subtick_moves_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      18,
      this->subtick_moves(static_cast<int>(i)),
      output);
  }

  // optional bytes move_crc = 19;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      19, this->move_crc(), output);
  }

  // optional uint32 consumed_server_angle_changes = 20;
  if (cached_has_bits & 0x00002000u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(20, this->consumed_server_angle_changes(), output);
  }

  // optional int32 cmd_flags = 21;
  if (cached_has_bits & 0x00004000u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(21, this->cmd_flags(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CBaseUserCmdPB)
}

::google::protobuf::uint8* CBaseUserCmdPB::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CBaseUserCmdPB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 legacy_command_number = 1;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->legacy_command_number(), target);
  }

  // optional int32 client_tick = 2;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->client_tick(), target);
  }

  // optional .CInButtonStatePB buttons_pb = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::buttons_pb(this), target);
  }

  // optional .CMsgQAngle viewangles = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, HasBitSetters::viewangles(this), target);
  }

  // optional float forwardmove = 5;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->forwardmove(), target);
  }

  // optional float leftmove = 6;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->leftmove(), target);
  }

  // optional float upmove = 7;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->upmove(), target);
  }

  // optional int32 impulse = 8;
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->impulse(), target);
  }

  // optional int32 weaponselect = 9;
  if (cached_has_bits & 0x00000200u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->weaponselect(), target);
  }

  // optional int32 random_seed = 10;
  if (cached_has_bits & 0x00000400u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(10, this->random_seed(), target);
  }

  // optional int32 mousedx = 11;
  if (cached_has_bits & 0x00000800u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(11, this->mousedx(), target);
  }

  // optional int32 mousedy = 12;
  if (cached_has_bits & 0x00001000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(12, this->mousedy(), target);
  }

  // optional uint32 pawn_entity_handle = 14 [default = 16777215];
  if (cached_has_bits & 0x00008000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(14, this->pawn_entity_handle(), target);
  }

  // repeated .CSubtickMoveStep subtick_moves = 18;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->subtick_moves_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        18, this->subtick_moves(static_cast<int>(i)), target);
  }

  // optional bytes move_crc = 19;
  if (cached_has_bits & 0x00000001u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        19, this->move_crc(), target);
  }

  // optional uint32 consumed_server_angle_changes = 20;
  if (cached_has_bits & 0x00002000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(20, this->consumed_server_angle_changes(), target);
  }

  // optional int32 cmd_flags = 21;
  if (cached_has_bits & 0x00004000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(21, this->cmd_flags(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CBaseUserCmdPB)
  return target;
}

size_t CBaseUserCmdPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CBaseUserCmdPB)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .CSubtickMoveStep subtick_moves = 18;
  {
    unsigned int count = static_cast<unsigned int>(this->subtick_moves_size());
    total_size += 2UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->subtick_moves(static_cast<int>(i)));
    }
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes move_crc = 19;
    if (cached_has_bits & 0x00000001u) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->move_crc());
    }

    // optional .CInButtonStatePB buttons_pb = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *buttons_pb_);
    }

    // optional .CMsgQAngle viewangles = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *viewangles_);
    }

    // optional int32 legacy_command_number = 1;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->legacy_command_number());
    }

    // optional int32 client_tick = 2;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->client_tick());
    }

    // optional float forwardmove = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 4;
    }

    // optional float leftmove = 6;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + 4;
    }

    // optional float upmove = 7;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + 4;
    }

  }
  if (cached_has_bits & 0x0000ff00u) {
    // optional int32 impulse = 8;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->impulse());
    }

    // optional int32 weaponselect = 9;
    if (cached_has_bits & 0x00000200u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->weaponselect());
    }

    // optional int32 random_seed = 10;
    if (cached_has_bits & 0x00000400u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->random_seed());
    }

    // optional int32 mousedx = 11;
    if (cached_has_bits & 0x00000800u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->mousedx());
    }

    // optional int32 mousedy = 12;
    if (cached_has_bits & 0x00001000u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->mousedy());
    }

    // optional uint32 consumed_server_angle_changes = 20;
    if (cached_has_bits & 0x00002000u) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->consumed_server_angle_changes());
    }

    // optional int32 cmd_flags = 21;
    if (cached_has_bits & 0x00004000u) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cmd_flags());
    }

    // optional uint32 pawn_entity_handle = 14 [default = 16777215];
    if (cached_has_bits & 0x00008000u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->pawn_entity_handle());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CBaseUserCmdPB::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CBaseUserCmdPB)
  GOOGLE_DCHECK_NE(&from, this);
  const CBaseUserCmdPB* source =
      ::google::protobuf::DynamicCastToGenerated<CBaseUserCmdPB>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CBaseUserCmdPB)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CBaseUserCmdPB)
    MergeFrom(*source);
  }
}

void CBaseUserCmdPB::MergeFrom(const CBaseUserCmdPB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CBaseUserCmdPB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  subtick_moves_.MergeFrom(from.subtick_moves_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      move_crc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.move_crc_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_buttons_pb()->::CInButtonStatePB::MergeFrom(from.buttons_pb());
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_viewangles()->::CMsgQAngle::MergeFrom(from.viewangles());
    }
    if (cached_has_bits & 0x00000008u) {
      legacy_command_number_ = from.legacy_command_number_;
    }
    if (cached_has_bits & 0x00000010u) {
      client_tick_ = from.client_tick_;
    }
    if (cached_has_bits & 0x00000020u) {
      forwardmove_ = from.forwardmove_;
    }
    if (cached_has_bits & 0x00000040u) {
      leftmove_ = from.leftmove_;
    }
    if (cached_has_bits & 0x00000080u) {
      upmove_ = from.upmove_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x0000ff00u) {
    if (cached_has_bits & 0x00000100u) {
      impulse_ = from.impulse_;
    }
    if (cached_has_bits & 0x00000200u) {
      weaponselect_ = from.weaponselect_;
    }
    if (cached_has_bits & 0x00000400u) {
      random_seed_ = from.random_seed_;
    }
    if (cached_has_bits & 0x00000800u) {
      mousedx_ = from.mousedx_;
    }
    if (cached_has_bits & 0x00001000u) {
      mousedy_ = from.mousedy_;
    }
    if (cached_has_bits & 0x00002000u) {
      consumed_server_angle_changes_ = from.consumed_server_angle_changes_;
    }
    if (cached_has_bits & 0x00004000u) {
      cmd_flags_ = from.cmd_flags_;
    }
    if (cached_has_bits & 0x00008000u) {
      pawn_entity_handle_ = from.pawn_entity_handle_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CBaseUserCmdPB::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CBaseUserCmdPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CBaseUserCmdPB::CopyFrom(const CBaseUserCmdPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CBaseUserCmdPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CBaseUserCmdPB::IsInitialized() const {
  return true;
}

void CBaseUserCmdPB::Swap(CBaseUserCmdPB* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CBaseUserCmdPB::InternalSwap(CBaseUserCmdPB* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  CastToBase(&subtick_moves_)->InternalSwap(CastToBase(&other->subtick_moves_));
  move_crc_.Swap(&other->move_crc_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(buttons_pb_, other->buttons_pb_);
  swap(viewangles_, other->viewangles_);
  swap(legacy_command_number_, other->legacy_command_number_);
  swap(client_tick_, other->client_tick_);
  swap(forwardmove_, other->forwardmove_);
  swap(leftmove_, other->leftmove_);
  swap(upmove_, other->upmove_);
  swap(impulse_, other->impulse_);
  swap(weaponselect_, other->weaponselect_);
  swap(random_seed_, other->random_seed_);
  swap(mousedx_, other->mousedx_);
  swap(mousedy_, other->mousedy_);
  swap(consumed_server_angle_changes_, other->consumed_server_angle_changes_);
  swap(cmd_flags_, other->cmd_flags_);
  swap(pawn_entity_handle_, other->pawn_entity_handle_);
}

::google::protobuf::Metadata CBaseUserCmdPB::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_usercmd_2eproto);
  return ::file_level_metadata_usercmd_2eproto[kIndexInFileMessages];
}


// ===================================================================

void CUserCmdBasePB::InitAsDefaultInstance() {
  ::_CUserCmdBasePB_default_instance_._instance.get_mutable()->base_ = const_cast< ::CBaseUserCmdPB*>(
      ::CBaseUserCmdPB::internal_default_instance());
}
class CUserCmdBasePB::HasBitSetters {
 public:
  static const ::CBaseUserCmdPB& base(const CUserCmdBasePB* msg);
  static void set_has_base(CUserCmdBasePB* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

const ::CBaseUserCmdPB&
CUserCmdBasePB::HasBitSetters::base(const CUserCmdBasePB* msg) {
  return *msg->base_;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CUserCmdBasePB::kBaseFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CUserCmdBasePB::CUserCmdBasePB()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CUserCmdBasePB)
}
CUserCmdBasePB::CUserCmdBasePB(const CUserCmdBasePB& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_base()) {
    base_ = new ::CBaseUserCmdPB(*from.base_);
  } else {
    base_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:CUserCmdBasePB)
}

void CUserCmdBasePB::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_CUserCmdBasePB_usercmd_2eproto.base);
  base_ = nullptr;
}

CUserCmdBasePB::~CUserCmdBasePB() {
  // @@protoc_insertion_point(destructor:CUserCmdBasePB)
  SharedDtor();
}

void CUserCmdBasePB::SharedDtor() {
  if (this != internal_default_instance()) delete base_;
}

void CUserCmdBasePB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CUserCmdBasePB& CUserCmdBasePB::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_CUserCmdBasePB_usercmd_2eproto.base);
  return *internal_default_instance();
}


void CUserCmdBasePB::Clear() {
// @@protoc_insertion_point(message_clear_start:CUserCmdBasePB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(base_ != nullptr);
    base_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* CUserCmdBasePB::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<CUserCmdBasePB*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional .CBaseUserCmdPB base = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::CBaseUserCmdPB::_InternalParse;
        object = msg->mutable_base();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool CUserCmdBasePB::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CUserCmdBasePB)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .CBaseUserCmdPB base = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_base()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CUserCmdBasePB)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CUserCmdBasePB)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void CUserCmdBasePB::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CUserCmdBasePB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .CBaseUserCmdPB base = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::base(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CUserCmdBasePB)
}

::google::protobuf::uint8* CUserCmdBasePB::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CUserCmdBasePB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .CBaseUserCmdPB base = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::base(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CUserCmdBasePB)
  return target;
}

size_t CUserCmdBasePB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CUserCmdBasePB)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .CBaseUserCmdPB base = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *base_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CUserCmdBasePB::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CUserCmdBasePB)
  GOOGLE_DCHECK_NE(&from, this);
  const CUserCmdBasePB* source =
      ::google::protobuf::DynamicCastToGenerated<CUserCmdBasePB>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CUserCmdBasePB)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CUserCmdBasePB)
    MergeFrom(*source);
  }
}

void CUserCmdBasePB::MergeFrom(const CUserCmdBasePB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CUserCmdBasePB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_base()) {
    mutable_base()->::CBaseUserCmdPB::MergeFrom(from.base());
  }
}

void CUserCmdBasePB::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CUserCmdBasePB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CUserCmdBasePB::CopyFrom(const CUserCmdBasePB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CUserCmdBasePB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CUserCmdBasePB::IsInitialized() const {
  return true;
}

void CUserCmdBasePB::Swap(CUserCmdBasePB* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CUserCmdBasePB::InternalSwap(CUserCmdBasePB* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(base_, other->base_);
}

::google::protobuf::Metadata CUserCmdBasePB::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_usercmd_2eproto);
  return ::file_level_metadata_usercmd_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::CInButtonStatePB* Arena::CreateMaybeMessage< ::CInButtonStatePB >(Arena* arena) {
  return Arena::CreateInternal< ::CInButtonStatePB >(arena);
}
template<> PROTOBUF_NOINLINE ::CSubtickMoveStep* Arena::CreateMaybeMessage< ::CSubtickMoveStep >(Arena* arena) {
  return Arena::CreateInternal< ::CSubtickMoveStep >(arena);
}
template<> PROTOBUF_NOINLINE ::CBaseUserCmdPB* Arena::CreateMaybeMessage< ::CBaseUserCmdPB >(Arena* arena) {
  return Arena::CreateInternal< ::CBaseUserCmdPB >(arena);
}
template<> PROTOBUF_NOINLINE ::CUserCmdBasePB* Arena::CreateMaybeMessage< ::CUserCmdBasePB >(Arena* arena) {
  return Arena::CreateInternal< ::CUserCmdBasePB >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
