// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usercmd.proto

#ifndef PROTOBUF_INCLUDED_usercmd_2eproto
#define PROTOBUF_INCLUDED_usercmd_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "networkbasetypes.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_usercmd_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_usercmd_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_usercmd_2eproto();
class CBaseUserCmdPB;
class CBaseUserCmdPBDefaultTypeInternal;
extern CBaseUserCmdPBDefaultTypeInternal _CBaseUserCmdPB_default_instance_;
class CInButtonStatePB;
class CInButtonStatePBDefaultTypeInternal;
extern CInButtonStatePBDefaultTypeInternal _CInButtonStatePB_default_instance_;
class CSubtickMoveStep;
class CSubtickMoveStepDefaultTypeInternal;
extern CSubtickMoveStepDefaultTypeInternal _CSubtickMoveStep_default_instance_;
class CUserCmdBasePB;
class CUserCmdBasePBDefaultTypeInternal;
extern CUserCmdBasePBDefaultTypeInternal _CUserCmdBasePB_default_instance_;
namespace google {
namespace protobuf {
template<> ::CBaseUserCmdPB* Arena::CreateMaybeMessage<::CBaseUserCmdPB>(Arena*);
template<> ::CInButtonStatePB* Arena::CreateMaybeMessage<::CInButtonStatePB>(Arena*);
template<> ::CSubtickMoveStep* Arena::CreateMaybeMessage<::CSubtickMoveStep>(Arena*);
template<> ::CUserCmdBasePB* Arena::CreateMaybeMessage<::CUserCmdBasePB>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class CInButtonStatePB final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CInButtonStatePB) */ {
 public:
  CInButtonStatePB();
  virtual ~CInButtonStatePB();

  CInButtonStatePB(const CInButtonStatePB& from);

  inline CInButtonStatePB& operator=(const CInButtonStatePB& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CInButtonStatePB(CInButtonStatePB&& from) noexcept
    : CInButtonStatePB() {
    *this = ::std::move(from);
  }

  inline CInButtonStatePB& operator=(CInButtonStatePB&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CInButtonStatePB& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CInButtonStatePB* internal_default_instance() {
    return reinterpret_cast<const CInButtonStatePB*>(
               &_CInButtonStatePB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CInButtonStatePB* other);
  friend void swap(CInButtonStatePB& a, CInButtonStatePB& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CInButtonStatePB* New() const final {
    return CreateMaybeMessage<CInButtonStatePB>(nullptr);
  }

  CInButtonStatePB* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CInButtonStatePB>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CInButtonStatePB& from);
  void MergeFrom(const CInButtonStatePB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CInButtonStatePB* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 buttonstate1 = 1;
  bool has_buttonstate1() const;
  void clear_buttonstate1();
  static const int kButtonstate1FieldNumber = 1;
  ::google::protobuf::uint64 buttonstate1() const;
  void set_buttonstate1(::google::protobuf::uint64 value);

  // optional uint64 buttonstate2 = 2;
  bool has_buttonstate2() const;
  void clear_buttonstate2();
  static const int kButtonstate2FieldNumber = 2;
  ::google::protobuf::uint64 buttonstate2() const;
  void set_buttonstate2(::google::protobuf::uint64 value);

  // optional uint64 buttonstate3 = 3;
  bool has_buttonstate3() const;
  void clear_buttonstate3();
  static const int kButtonstate3FieldNumber = 3;
  ::google::protobuf::uint64 buttonstate3() const;
  void set_buttonstate3(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:CInButtonStatePB)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint64 buttonstate1_;
  ::google::protobuf::uint64 buttonstate2_;
  ::google::protobuf::uint64 buttonstate3_;
  friend struct ::TableStruct_usercmd_2eproto;
};
// -------------------------------------------------------------------

class CSubtickMoveStep final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSubtickMoveStep) */ {
 public:
  CSubtickMoveStep();
  virtual ~CSubtickMoveStep();

  CSubtickMoveStep(const CSubtickMoveStep& from);

  inline CSubtickMoveStep& operator=(const CSubtickMoveStep& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CSubtickMoveStep(CSubtickMoveStep&& from) noexcept
    : CSubtickMoveStep() {
    *this = ::std::move(from);
  }

  inline CSubtickMoveStep& operator=(CSubtickMoveStep&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CSubtickMoveStep& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CSubtickMoveStep* internal_default_instance() {
    return reinterpret_cast<const CSubtickMoveStep*>(
               &_CSubtickMoveStep_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CSubtickMoveStep* other);
  friend void swap(CSubtickMoveStep& a, CSubtickMoveStep& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CSubtickMoveStep* New() const final {
    return CreateMaybeMessage<CSubtickMoveStep>(nullptr);
  }

  CSubtickMoveStep* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CSubtickMoveStep>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CSubtickMoveStep& from);
  void MergeFrom(const CSubtickMoveStep& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CSubtickMoveStep* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 button = 1;
  bool has_button() const;
  void clear_button();
  static const int kButtonFieldNumber = 1;
  ::google::protobuf::uint64 button() const;
  void set_button(::google::protobuf::uint64 value);

  // optional bool pressed = 2;
  bool has_pressed() const;
  void clear_pressed();
  static const int kPressedFieldNumber = 2;
  bool pressed() const;
  void set_pressed(bool value);

  // optional float when = 3;
  bool has_when() const;
  void clear_when();
  static const int kWhenFieldNumber = 3;
  float when() const;
  void set_when(float value);

  // optional float analog_forward_delta = 4;
  bool has_analog_forward_delta() const;
  void clear_analog_forward_delta();
  static const int kAnalogForwardDeltaFieldNumber = 4;
  float analog_forward_delta() const;
  void set_analog_forward_delta(float value);

  // optional float analog_left_delta = 5;
  bool has_analog_left_delta() const;
  void clear_analog_left_delta();
  static const int kAnalogLeftDeltaFieldNumber = 5;
  float analog_left_delta() const;
  void set_analog_left_delta(float value);

  // @@protoc_insertion_point(class_scope:CSubtickMoveStep)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint64 button_;
  bool pressed_;
  float when_;
  float analog_forward_delta_;
  float analog_left_delta_;
  friend struct ::TableStruct_usercmd_2eproto;
};
// -------------------------------------------------------------------

class CBaseUserCmdPB final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CBaseUserCmdPB) */ {
 public:
  CBaseUserCmdPB();
  virtual ~CBaseUserCmdPB();

  CBaseUserCmdPB(const CBaseUserCmdPB& from);

  inline CBaseUserCmdPB& operator=(const CBaseUserCmdPB& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CBaseUserCmdPB(CBaseUserCmdPB&& from) noexcept
    : CBaseUserCmdPB() {
    *this = ::std::move(from);
  }

  inline CBaseUserCmdPB& operator=(CBaseUserCmdPB&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CBaseUserCmdPB& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CBaseUserCmdPB* internal_default_instance() {
    return reinterpret_cast<const CBaseUserCmdPB*>(
               &_CBaseUserCmdPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(CBaseUserCmdPB* other);
  friend void swap(CBaseUserCmdPB& a, CBaseUserCmdPB& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CBaseUserCmdPB* New() const final {
    return CreateMaybeMessage<CBaseUserCmdPB>(nullptr);
  }

  CBaseUserCmdPB* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CBaseUserCmdPB>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CBaseUserCmdPB& from);
  void MergeFrom(const CBaseUserCmdPB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CBaseUserCmdPB* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .CSubtickMoveStep subtick_moves = 18;
  int subtick_moves_size() const;
  void clear_subtick_moves();
  static const int kSubtickMovesFieldNumber = 18;
  ::CSubtickMoveStep* mutable_subtick_moves(int index);
  ::google::protobuf::RepeatedPtrField< ::CSubtickMoveStep >*
      mutable_subtick_moves();
  const ::CSubtickMoveStep& subtick_moves(int index) const;
  ::CSubtickMoveStep* add_subtick_moves();
  const ::google::protobuf::RepeatedPtrField< ::CSubtickMoveStep >&
      subtick_moves() const;

  // optional bytes move_crc = 19;
  bool has_move_crc() const;
  void clear_move_crc();
  static const int kMoveCrcFieldNumber = 19;
  const ::std::string& move_crc() const;
  void set_move_crc(const ::std::string& value);
  #if LANG_CXX11
  void set_move_crc(::std::string&& value);
  #endif
  void set_move_crc(const char* value);
  void set_move_crc(const void* value, size_t size);
  ::std::string* mutable_move_crc();
  ::std::string* release_move_crc();
  void set_allocated_move_crc(::std::string* move_crc);

  // optional .CInButtonStatePB buttons_pb = 3;
  bool has_buttons_pb() const;
  void clear_buttons_pb();
  static const int kButtonsPbFieldNumber = 3;
  const ::CInButtonStatePB& buttons_pb() const;
  ::CInButtonStatePB* release_buttons_pb();
  ::CInButtonStatePB* mutable_buttons_pb();
  void set_allocated_buttons_pb(::CInButtonStatePB* buttons_pb);

  // optional .CMsgQAngle viewangles = 4;
  bool has_viewangles() const;
  void clear_viewangles();
  static const int kViewanglesFieldNumber = 4;
  const ::CMsgQAngle& viewangles() const;
  ::CMsgQAngle* release_viewangles();
  ::CMsgQAngle* mutable_viewangles();
  void set_allocated_viewangles(::CMsgQAngle* viewangles);

  // optional int32 legacy_command_number = 1;
  bool has_legacy_command_number() const;
  void clear_legacy_command_number();
  static const int kLegacyCommandNumberFieldNumber = 1;
  ::google::protobuf::int32 legacy_command_number() const;
  void set_legacy_command_number(::google::protobuf::int32 value);

  // optional int32 client_tick = 2;
  bool has_client_tick() const;
  void clear_client_tick();
  static const int kClientTickFieldNumber = 2;
  ::google::protobuf::int32 client_tick() const;
  void set_client_tick(::google::protobuf::int32 value);

  // optional float forwardmove = 5;
  bool has_forwardmove() const;
  void clear_forwardmove();
  static const int kForwardmoveFieldNumber = 5;
  float forwardmove() const;
  void set_forwardmove(float value);

  // optional float leftmove = 6;
  bool has_leftmove() const;
  void clear_leftmove();
  static const int kLeftmoveFieldNumber = 6;
  float leftmove() const;
  void set_leftmove(float value);

  // optional float upmove = 7;
  bool has_upmove() const;
  void clear_upmove();
  static const int kUpmoveFieldNumber = 7;
  float upmove() const;
  void set_upmove(float value);

  // optional int32 impulse = 8;
  bool has_impulse() const;
  void clear_impulse();
  static const int kImpulseFieldNumber = 8;
  ::google::protobuf::int32 impulse() const;
  void set_impulse(::google::protobuf::int32 value);

  // optional int32 weaponselect = 9;
  bool has_weaponselect() const;
  void clear_weaponselect();
  static const int kWeaponselectFieldNumber = 9;
  ::google::protobuf::int32 weaponselect() const;
  void set_weaponselect(::google::protobuf::int32 value);

  // optional int32 random_seed = 10;
  bool has_random_seed() const;
  void clear_random_seed();
  static const int kRandomSeedFieldNumber = 10;
  ::google::protobuf::int32 random_seed() const;
  void set_random_seed(::google::protobuf::int32 value);

  // optional int32 mousedx = 11;
  bool has_mousedx() const;
  void clear_mousedx();
  static const int kMousedxFieldNumber = 11;
  ::google::protobuf::int32 mousedx() const;
  void set_mousedx(::google::protobuf::int32 value);

  // optional int32 mousedy = 12;
  bool has_mousedy() const;
  void clear_mousedy();
  static const int kMousedyFieldNumber = 12;
  ::google::protobuf::int32 mousedy() const;
  void set_mousedy(::google::protobuf::int32 value);

  // optional uint32 consumed_server_angle_changes = 20;
  bool has_consumed_server_angle_changes() const;
  void clear_consumed_server_angle_changes();
  static const int kConsumedServerAngleChangesFieldNumber = 20;
  ::google::protobuf::uint32 consumed_server_angle_changes() const;
  void set_consumed_server_angle_changes(::google::protobuf::uint32 value);

  // optional int32 cmd_flags = 21;
  bool has_cmd_flags() const;
  void clear_cmd_flags();
  static const int kCmdFlagsFieldNumber = 21;
  ::google::protobuf::int32 cmd_flags() const;
  void set_cmd_flags(::google::protobuf::int32 value);

  // optional uint32 pawn_entity_handle = 14 [default = 16777215];
  bool has_pawn_entity_handle() const;
  void clear_pawn_entity_handle();
  static const int kPawnEntityHandleFieldNumber = 14;
  ::google::protobuf::uint32 pawn_entity_handle() const;
  void set_pawn_entity_handle(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CBaseUserCmdPB)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::CSubtickMoveStep > subtick_moves_;
  ::google::protobuf::internal::ArenaStringPtr move_crc_;
  ::CInButtonStatePB* buttons_pb_;
  ::CMsgQAngle* viewangles_;
  ::google::protobuf::int32 legacy_command_number_;
  ::google::protobuf::int32 client_tick_;
  float forwardmove_;
  float leftmove_;
  float upmove_;
  ::google::protobuf::int32 impulse_;
  ::google::protobuf::int32 weaponselect_;
  ::google::protobuf::int32 random_seed_;
  ::google::protobuf::int32 mousedx_;
  ::google::protobuf::int32 mousedy_;
  ::google::protobuf::uint32 consumed_server_angle_changes_;
  ::google::protobuf::int32 cmd_flags_;
  ::google::protobuf::uint32 pawn_entity_handle_;
  friend struct ::TableStruct_usercmd_2eproto;
};
// -------------------------------------------------------------------

class CUserCmdBasePB final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CUserCmdBasePB) */ {
 public:
  CUserCmdBasePB();
  virtual ~CUserCmdBasePB();

  CUserCmdBasePB(const CUserCmdBasePB& from);

  inline CUserCmdBasePB& operator=(const CUserCmdBasePB& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CUserCmdBasePB(CUserCmdBasePB&& from) noexcept
    : CUserCmdBasePB() {
    *this = ::std::move(from);
  }

  inline CUserCmdBasePB& operator=(CUserCmdBasePB&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CUserCmdBasePB& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CUserCmdBasePB* internal_default_instance() {
    return reinterpret_cast<const CUserCmdBasePB*>(
               &_CUserCmdBasePB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(CUserCmdBasePB* other);
  friend void swap(CUserCmdBasePB& a, CUserCmdBasePB& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CUserCmdBasePB* New() const final {
    return CreateMaybeMessage<CUserCmdBasePB>(nullptr);
  }

  CUserCmdBasePB* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CUserCmdBasePB>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CUserCmdBasePB& from);
  void MergeFrom(const CUserCmdBasePB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CUserCmdBasePB* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CBaseUserCmdPB base = 1;
  bool has_base() const;
  void clear_base();
  static const int kBaseFieldNumber = 1;
  const ::CBaseUserCmdPB& base() const;
  ::CBaseUserCmdPB* release_base();
  ::CBaseUserCmdPB* mutable_base();
  void set_allocated_base(::CBaseUserCmdPB* base);

  // @@protoc_insertion_point(class_scope:CUserCmdBasePB)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::CBaseUserCmdPB* base_;
  friend struct ::TableStruct_usercmd_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CInButtonStatePB

// optional uint64 buttonstate1 = 1;
inline bool CInButtonStatePB::has_buttonstate1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CInButtonStatePB::clear_buttonstate1() {
  buttonstate1_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::uint64 CInButtonStatePB::buttonstate1() const {
  // @@protoc_insertion_point(field_get:CInButtonStatePB.buttonstate1)
  return buttonstate1_;
}
inline void CInButtonStatePB::set_buttonstate1(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  buttonstate1_ = value;
  // @@protoc_insertion_point(field_set:CInButtonStatePB.buttonstate1)
}

// optional uint64 buttonstate2 = 2;
inline bool CInButtonStatePB::has_buttonstate2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CInButtonStatePB::clear_buttonstate2() {
  buttonstate2_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::uint64 CInButtonStatePB::buttonstate2() const {
  // @@protoc_insertion_point(field_get:CInButtonStatePB.buttonstate2)
  return buttonstate2_;
}
inline void CInButtonStatePB::set_buttonstate2(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  buttonstate2_ = value;
  // @@protoc_insertion_point(field_set:CInButtonStatePB.buttonstate2)
}

// optional uint64 buttonstate3 = 3;
inline bool CInButtonStatePB::has_buttonstate3() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CInButtonStatePB::clear_buttonstate3() {
  buttonstate3_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::uint64 CInButtonStatePB::buttonstate3() const {
  // @@protoc_insertion_point(field_get:CInButtonStatePB.buttonstate3)
  return buttonstate3_;
}
inline void CInButtonStatePB::set_buttonstate3(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000004u;
  buttonstate3_ = value;
  // @@protoc_insertion_point(field_set:CInButtonStatePB.buttonstate3)
}

// -------------------------------------------------------------------

// CSubtickMoveStep

// optional uint64 button = 1;
inline bool CSubtickMoveStep::has_button() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSubtickMoveStep::clear_button() {
  button_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::uint64 CSubtickMoveStep::button() const {
  // @@protoc_insertion_point(field_get:CSubtickMoveStep.button)
  return button_;
}
inline void CSubtickMoveStep::set_button(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  button_ = value;
  // @@protoc_insertion_point(field_set:CSubtickMoveStep.button)
}

// optional bool pressed = 2;
inline bool CSubtickMoveStep::has_pressed() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CSubtickMoveStep::clear_pressed() {
  pressed_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool CSubtickMoveStep::pressed() const {
  // @@protoc_insertion_point(field_get:CSubtickMoveStep.pressed)
  return pressed_;
}
inline void CSubtickMoveStep::set_pressed(bool value) {
  _has_bits_[0] |= 0x00000002u;
  pressed_ = value;
  // @@protoc_insertion_point(field_set:CSubtickMoveStep.pressed)
}

// optional float when = 3;
inline bool CSubtickMoveStep::has_when() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CSubtickMoveStep::clear_when() {
  when_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline float CSubtickMoveStep::when() const {
  // @@protoc_insertion_point(field_get:CSubtickMoveStep.when)
  return when_;
}
inline void CSubtickMoveStep::set_when(float value) {
  _has_bits_[0] |= 0x00000004u;
  when_ = value;
  // @@protoc_insertion_point(field_set:CSubtickMoveStep.when)
}

// optional float analog_forward_delta = 4;
inline bool CSubtickMoveStep::has_analog_forward_delta() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CSubtickMoveStep::clear_analog_forward_delta() {
  analog_forward_delta_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline float CSubtickMoveStep::analog_forward_delta() const {
  // @@protoc_insertion_point(field_get:CSubtickMoveStep.analog_forward_delta)
  return analog_forward_delta_;
}
inline void CSubtickMoveStep::set_analog_forward_delta(float value) {
  _has_bits_[0] |= 0x00000008u;
  analog_forward_delta_ = value;
  // @@protoc_insertion_point(field_set:CSubtickMoveStep.analog_forward_delta)
}

// optional float analog_left_delta = 5;
inline bool CSubtickMoveStep::has_analog_left_delta() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CSubtickMoveStep::clear_analog_left_delta() {
  analog_left_delta_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline float CSubtickMoveStep::analog_left_delta() const {
  // @@protoc_insertion_point(field_get:CSubtickMoveStep.analog_left_delta)
  return analog_left_delta_;
}
inline void CSubtickMoveStep::set_analog_left_delta(float value) {
  _has_bits_[0] |= 0x00000010u;
  analog_left_delta_ = value;
  // @@protoc_insertion_point(field_set:CSubtickMoveStep.analog_left_delta)
}

// -------------------------------------------------------------------

// CBaseUserCmdPB

// optional int32 legacy_command_number = 1;
inline bool CBaseUserCmdPB::has_legacy_command_number() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CBaseUserCmdPB::clear_legacy_command_number() {
  legacy_command_number_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 CBaseUserCmdPB::legacy_command_number() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.legacy_command_number)
  return legacy_command_number_;
}
inline void CBaseUserCmdPB::set_legacy_command_number(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  legacy_command_number_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.legacy_command_number)
}

// optional int32 client_tick = 2;
inline bool CBaseUserCmdPB::has_client_tick() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CBaseUserCmdPB::clear_client_tick() {
  client_tick_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::int32 CBaseUserCmdPB::client_tick() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.client_tick)
  return client_tick_;
}
inline void CBaseUserCmdPB::set_client_tick(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  client_tick_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.client_tick)
}

// optional .CInButtonStatePB buttons_pb = 3;
inline bool CBaseUserCmdPB::has_buttons_pb() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CBaseUserCmdPB::clear_buttons_pb() {
  if (buttons_pb_ != nullptr) buttons_pb_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::CInButtonStatePB& CBaseUserCmdPB::buttons_pb() const {
  const ::CInButtonStatePB* p = buttons_pb_;
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.buttons_pb)
  return p != nullptr ? *p : *reinterpret_cast<const ::CInButtonStatePB*>(
      &::_CInButtonStatePB_default_instance_);
}
inline ::CInButtonStatePB* CBaseUserCmdPB::release_buttons_pb() {
  // @@protoc_insertion_point(field_release:CBaseUserCmdPB.buttons_pb)
  _has_bits_[0] &= ~0x00000002u;
  ::CInButtonStatePB* temp = buttons_pb_;
  buttons_pb_ = nullptr;
  return temp;
}
inline ::CInButtonStatePB* CBaseUserCmdPB::mutable_buttons_pb() {
  _has_bits_[0] |= 0x00000002u;
  if (buttons_pb_ == nullptr) {
    auto* p = CreateMaybeMessage<::CInButtonStatePB>(GetArenaNoVirtual());
    buttons_pb_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CBaseUserCmdPB.buttons_pb)
  return buttons_pb_;
}
inline void CBaseUserCmdPB::set_allocated_buttons_pb(::CInButtonStatePB* buttons_pb) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete buttons_pb_;
  }
  if (buttons_pb) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      buttons_pb = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, buttons_pb, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  buttons_pb_ = buttons_pb;
  // @@protoc_insertion_point(field_set_allocated:CBaseUserCmdPB.buttons_pb)
}

// optional .CMsgQAngle viewangles = 4;
inline bool CBaseUserCmdPB::has_viewangles() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline const ::CMsgQAngle& CBaseUserCmdPB::viewangles() const {
  const ::CMsgQAngle* p = viewangles_;
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.viewangles)
  return p != nullptr ? *p : *reinterpret_cast<const ::CMsgQAngle*>(
      &::_CMsgQAngle_default_instance_);
}
inline ::CMsgQAngle* CBaseUserCmdPB::release_viewangles() {
  // @@protoc_insertion_point(field_release:CBaseUserCmdPB.viewangles)
  _has_bits_[0] &= ~0x00000004u;
  ::CMsgQAngle* temp = viewangles_;
  viewangles_ = nullptr;
  return temp;
}
inline ::CMsgQAngle* CBaseUserCmdPB::mutable_viewangles() {
  _has_bits_[0] |= 0x00000004u;
  if (viewangles_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMsgQAngle>(GetArenaNoVirtual());
    viewangles_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CBaseUserCmdPB.viewangles)
  return viewangles_;
}
inline void CBaseUserCmdPB::set_allocated_viewangles(::CMsgQAngle* viewangles) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(viewangles_);
  }
  if (viewangles) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      viewangles = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, viewangles, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  viewangles_ = viewangles;
  // @@protoc_insertion_point(field_set_allocated:CBaseUserCmdPB.viewangles)
}

// optional float forwardmove = 5;
inline bool CBaseUserCmdPB::has_forwardmove() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CBaseUserCmdPB::clear_forwardmove() {
  forwardmove_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline float CBaseUserCmdPB::forwardmove() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.forwardmove)
  return forwardmove_;
}
inline void CBaseUserCmdPB::set_forwardmove(float value) {
  _has_bits_[0] |= 0x00000020u;
  forwardmove_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.forwardmove)
}

// optional float leftmove = 6;
inline bool CBaseUserCmdPB::has_leftmove() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CBaseUserCmdPB::clear_leftmove() {
  leftmove_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline float CBaseUserCmdPB::leftmove() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.leftmove)
  return leftmove_;
}
inline void CBaseUserCmdPB::set_leftmove(float value) {
  _has_bits_[0] |= 0x00000040u;
  leftmove_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.leftmove)
}

// optional float upmove = 7;
inline bool CBaseUserCmdPB::has_upmove() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void CBaseUserCmdPB::clear_upmove() {
  upmove_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline float CBaseUserCmdPB::upmove() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.upmove)
  return upmove_;
}
inline void CBaseUserCmdPB::set_upmove(float value) {
  _has_bits_[0] |= 0x00000080u;
  upmove_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.upmove)
}

// optional int32 impulse = 8;
inline bool CBaseUserCmdPB::has_impulse() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void CBaseUserCmdPB::clear_impulse() {
  impulse_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::google::protobuf::int32 CBaseUserCmdPB::impulse() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.impulse)
  return impulse_;
}
inline void CBaseUserCmdPB::set_impulse(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000100u;
  impulse_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.impulse)
}

// optional int32 weaponselect = 9;
inline bool CBaseUserCmdPB::has_weaponselect() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void CBaseUserCmdPB::clear_weaponselect() {
  weaponselect_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline ::google::protobuf::int32 CBaseUserCmdPB::weaponselect() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.weaponselect)
  return weaponselect_;
}
inline void CBaseUserCmdPB::set_weaponselect(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000200u;
  weaponselect_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.weaponselect)
}

// optional int32 random_seed = 10;
inline bool CBaseUserCmdPB::has_random_seed() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void CBaseUserCmdPB::clear_random_seed() {
  random_seed_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline ::google::protobuf::int32 CBaseUserCmdPB::random_seed() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.random_seed)
  return random_seed_;
}
inline void CBaseUserCmdPB::set_random_seed(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000400u;
  random_seed_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.random_seed)
}

// optional int32 mousedx = 11;
inline bool CBaseUserCmdPB::has_mousedx() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void CBaseUserCmdPB::clear_mousedx() {
  mousedx_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline ::google::protobuf::int32 CBaseUserCmdPB::mousedx() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.mousedx)
  return mousedx_;
}
inline void CBaseUserCmdPB::set_mousedx(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000800u;
  mousedx_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.mousedx)
}

// optional int32 mousedy = 12;
inline bool CBaseUserCmdPB::has_mousedy() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void CBaseUserCmdPB::clear_mousedy() {
  mousedy_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline ::google::protobuf::int32 CBaseUserCmdPB::mousedy() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.mousedy)
  return mousedy_;
}
inline void CBaseUserCmdPB::set_mousedy(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00001000u;
  mousedy_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.mousedy)
}

// optional uint32 pawn_entity_handle = 14 [default = 16777215];
inline bool CBaseUserCmdPB::has_pawn_entity_handle() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void CBaseUserCmdPB::clear_pawn_entity_handle() {
  pawn_entity_handle_ = 16777215u;
  _has_bits_[0] &= ~0x00008000u;
}
inline ::google::protobuf::uint32 CBaseUserCmdPB::pawn_entity_handle() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.pawn_entity_handle)
  return pawn_entity_handle_;
}
inline void CBaseUserCmdPB::set_pawn_entity_handle(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00008000u;
  pawn_entity_handle_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.pawn_entity_handle)
}

// repeated .CSubtickMoveStep subtick_moves = 18;
inline int CBaseUserCmdPB::subtick_moves_size() const {
  return subtick_moves_.size();
}
inline void CBaseUserCmdPB::clear_subtick_moves() {
  subtick_moves_.Clear();
}
inline ::CSubtickMoveStep* CBaseUserCmdPB::mutable_subtick_moves(int index) {
  // @@protoc_insertion_point(field_mutable:CBaseUserCmdPB.subtick_moves)
  return subtick_moves_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::CSubtickMoveStep >*
CBaseUserCmdPB::mutable_subtick_moves() {
  // @@protoc_insertion_point(field_mutable_list:CBaseUserCmdPB.subtick_moves)
  return &subtick_moves_;
}
inline const ::CSubtickMoveStep& CBaseUserCmdPB::subtick_moves(int index) const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.subtick_moves)
  return subtick_moves_.Get(index);
}
inline ::CSubtickMoveStep* CBaseUserCmdPB::add_subtick_moves() {
  // @@protoc_insertion_point(field_add:CBaseUserCmdPB.subtick_moves)
  return subtick_moves_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CSubtickMoveStep >&
CBaseUserCmdPB::subtick_moves() const {
  // @@protoc_insertion_point(field_list:CBaseUserCmdPB.subtick_moves)
  return subtick_moves_;
}

// optional bytes move_crc = 19;
inline bool CBaseUserCmdPB::has_move_crc() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CBaseUserCmdPB::clear_move_crc() {
  move_crc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& CBaseUserCmdPB::move_crc() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.move_crc)
  return move_crc_.GetNoArena();
}
inline void CBaseUserCmdPB::set_move_crc(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  move_crc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.move_crc)
}
#if LANG_CXX11
inline void CBaseUserCmdPB::set_move_crc(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  move_crc_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CBaseUserCmdPB.move_crc)
}
#endif
inline void CBaseUserCmdPB::set_move_crc(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  move_crc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CBaseUserCmdPB.move_crc)
}
inline void CBaseUserCmdPB::set_move_crc(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  move_crc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CBaseUserCmdPB.move_crc)
}
inline ::std::string* CBaseUserCmdPB::mutable_move_crc() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:CBaseUserCmdPB.move_crc)
  return move_crc_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CBaseUserCmdPB::release_move_crc() {
  // @@protoc_insertion_point(field_release:CBaseUserCmdPB.move_crc)
  if (!has_move_crc()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return move_crc_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CBaseUserCmdPB::set_allocated_move_crc(::std::string* move_crc) {
  if (move_crc != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  move_crc_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), move_crc);
  // @@protoc_insertion_point(field_set_allocated:CBaseUserCmdPB.move_crc)
}

// optional uint32 consumed_server_angle_changes = 20;
inline bool CBaseUserCmdPB::has_consumed_server_angle_changes() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void CBaseUserCmdPB::clear_consumed_server_angle_changes() {
  consumed_server_angle_changes_ = 0u;
  _has_bits_[0] &= ~0x00002000u;
}
inline ::google::protobuf::uint32 CBaseUserCmdPB::consumed_server_angle_changes() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.consumed_server_angle_changes)
  return consumed_server_angle_changes_;
}
inline void CBaseUserCmdPB::set_consumed_server_angle_changes(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00002000u;
  consumed_server_angle_changes_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.consumed_server_angle_changes)
}

// optional int32 cmd_flags = 21;
inline bool CBaseUserCmdPB::has_cmd_flags() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void CBaseUserCmdPB::clear_cmd_flags() {
  cmd_flags_ = 0;
  _has_bits_[0] &= ~0x00004000u;
}
inline ::google::protobuf::int32 CBaseUserCmdPB::cmd_flags() const {
  // @@protoc_insertion_point(field_get:CBaseUserCmdPB.cmd_flags)
  return cmd_flags_;
}
inline void CBaseUserCmdPB::set_cmd_flags(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00004000u;
  cmd_flags_ = value;
  // @@protoc_insertion_point(field_set:CBaseUserCmdPB.cmd_flags)
}

// -------------------------------------------------------------------

// CUserCmdBasePB

// optional .CBaseUserCmdPB base = 1;
inline bool CUserCmdBasePB::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CUserCmdBasePB::clear_base() {
  if (base_ != nullptr) base_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::CBaseUserCmdPB& CUserCmdBasePB::base() const {
  const ::CBaseUserCmdPB* p = base_;
  // @@protoc_insertion_point(field_get:CUserCmdBasePB.base)
  return p != nullptr ? *p : *reinterpret_cast<const ::CBaseUserCmdPB*>(
      &::_CBaseUserCmdPB_default_instance_);
}
inline ::CBaseUserCmdPB* CUserCmdBasePB::release_base() {
  // @@protoc_insertion_point(field_release:CUserCmdBasePB.base)
  _has_bits_[0] &= ~0x00000001u;
  ::CBaseUserCmdPB* temp = base_;
  base_ = nullptr;
  return temp;
}
inline ::CBaseUserCmdPB* CUserCmdBasePB::mutable_base() {
  _has_bits_[0] |= 0x00000001u;
  if (base_ == nullptr) {
    auto* p = CreateMaybeMessage<::CBaseUserCmdPB>(GetArenaNoVirtual());
    base_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CUserCmdBasePB.base)
  return base_;
}
inline void CUserCmdBasePB::set_allocated_base(::CBaseUserCmdPB* base) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete base_;
  }
  if (base) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      base = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, base, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  base_ = base;
  // @@protoc_insertion_point(field_set_allocated:CUserCmdBasePB.base)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_usercmd_2eproto
