use super::PatternHit;
use crate::analysis::{InterfaceMap, OffsetMap};
use std::collections::BTreeMap;

/// Map a DLL filename to the namespace stem we expose it under.
///
/// `client.dll` -> `client`         (cs2::offsets style)
/// `client.dll` -> `client_dll`     (cs2_dumper style, matches a2x)
fn ns_short(module: &str) -> String {
    module.trim_end_matches(".dll").replace('.', "_")
}

/// Sanitise a Pattern `name` field into a valid C++/Rust identifier.
/// Some entries in the database carry C++-style scoping like
/// `Engine::PVSManager_ptr` — that token can't appear inside a
/// `namespace { ... }` body without a syntax error, so flatten it.
fn sanitise_ident(name: &str) -> String {
    name.replace("::", "_")
        .replace(|c: char| !(c.is_ascii_alphanumeric() || c == '_'), "_")
}

/// Clean an offset symbol to the unified convention: no Hungarian `dw`
/// prefix and no `_ptr` suffix. `dwLocalPlayerPawn` -> `LocalPlayerPawn`,
/// `LocalPlayerController_ptr` -> `LocalPlayerController`.
fn clean_off_name(name: &str) -> String {
    let mut n = sanitise_ident(name);
    if let Some(s) = n.strip_suffix("_ptr") {
        n = s.to_string();
    }
    if n.starts_with("dw") && n[2..].chars().next().map(|c| c.is_ascii_uppercase()).unwrap_or(false) {
        n = n[2..].to_string();
    }
    n
}

/// Generate `sdk/offsets.hpp`.
///
/// The file holds two side-by-side namespace trees so any consumer
/// can pick the convention they already use:
///
/// * `cs2::offsets::<module>`        — every RIPREL Pattern hit
///   (`GameRules_ptr`, `LocalPlayerController_ptr`, …) keyed by the
///   exact name from `patterns::database`. This is the dumper's
///   own preferred layout.
/// * `cs2_dumper::offsets::<module>_dll` — drop-in compatible with
///   `a2x/cs2-dumper`'s `offsets.hpp`. Sourced from the live
///   pattern-scan analysis pass (`analysis::offsets`) so it carries
///   the canonical `dwLocalPlayerPawn`, `dwViewAngles`, `dwEntityList`,
///   `dwGameEntitySystem_highestEntityIndex`, `dwGlobalVars`, …
///   names every public CS2 cheat already uses.
pub fn render_offsets_hpp(hits: &[PatternHit], analysis: &OffsetMap, interfaces: &InterfaceMap) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk - https://cs2-sdk.com\n");
    s.push_str("// Resolved global RVAs, merged from the offset (pattern-scan) and\n");
    s.push_str("// Pattern (rip-relative) passes into one tree: offsets::<module>::Name\n");
    s.push_str("// (no dw / _ptr affixes).\n");
    s.push_str("#pragma once\n\n");
    s.push_str("#include <cstddef>\n");
    s.push_str("#include <cstdint>\n\n");

    // Merge both sources into one module -> (clean name -> rva) tree. The
    // pattern-scan pass (canonical dwXxx names) is inserted first so it wins
    // on a name clash; rip-relative Pattern globals fill in the rest.
    let mut merged: BTreeMap<String, BTreeMap<String, u64>> = BTreeMap::new();
    for (module, entries) in analysis {
        let m = merged.entry(ns_short(module)).or_default();
        for (name, rva) in entries {
            m.entry(clean_off_name(name)).or_insert(*rva as u64);
        }
    }
    for h in hits.iter().filter(|h| h.found && h.resolve == "riprel") {
        if let Some(rva) = h.rva {
            let m = merged.entry(ns_short(&h.module)).or_default();
            m.entry(clean_off_name(&h.name)).or_insert(rva as u64);
        }
    }
    // Registered interfaces. Each iface name maps to its singleton RVA — `mov`-style
    // factories (which need a runtime deref to reach the instance) get a `p` prefix
    // on the constant so the naming makes the deref requirement obvious to consumers.
    for (module, ifaces) in interfaces {
        let m = merged.entry(ns_short(module)).or_default();
        for (name, entry) in ifaces {
            let ident = if entry.needs_deref { format!("p{}", name) } else { name.clone() };
            m.entry(sanitise_ident(&ident)).or_insert(entry.rva as u64);
        }
    }

    s.push_str("namespace offsets {\n");
    for (module, entries) in &merged {
        s.push_str(&format!("    namespace {} {{\n", module));
        for (name, rva) in entries {
            s.push_str(&format!("        constexpr std::ptrdiff_t {} = 0x{:X};\n", name, rva));
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n");

    s
}

/// `sdk/offsets.json` — machine-readable mirror of the a2x block.
pub fn render_offsets_json(analysis: &OffsetMap) -> String {
    // Convert RVAs to hex strings so the JSON matches a2x's emitter byte for byte.
    let mut root: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    for (module, entries) in analysis {
        let mut inner = BTreeMap::new();
        for (name, rva) in entries {
            inner.insert(name.clone(), format!("0x{:X}", rva));
        }
        root.insert(module.clone(), inner);
    }
    serde_json::to_string_pretty(&root).unwrap_or_default()
}
