//! Multi-language emitters for resolved patterns.
//!
//! We already emit a hand-formatted [`patterns.json`].  This module adds
//! sibling files in the same set of languages the offset pass produces
//! (`.hpp`, `.rs`) so consumers can drop the file straight into
//! their project without writing a converter.
//!
//! Output is intentionally minimal — one constant per Pattern, named
//! after the Pattern, valued with the IDA-style byte **pattern**
//! (auto-synthesised at the resolved RVA when available, otherwise the
//! database pattern).  Consumers do their own pattern scanning at
//! runtime, which is build-portable and avoids leaking absolute
//! addresses into compiled artefacts.

use std::collections::BTreeMap;

use super::PatternHit;

/// Group resolved patterns by module so each emitter can render them as
/// nested namespaces / modules / classes. RIPREL (data-global) sigs are
/// included: their `pattern_synth` is null so `emit_pattern` yields the raw
/// instruction needle, which consumers scan and rip-resolve themselves.
fn grouped<'a>(hits: &'a [PatternHit]) -> BTreeMap<&'a str, Vec<&'a PatternHit>> {
    let mut out: BTreeMap<&'a str, Vec<&'a PatternHit>> = BTreeMap::new();
    for h in hits.iter().filter(|h| h.found) {
        out.entry(h.module.as_str()).or_default().push(h);
    }
    for v in out.values_mut() {
        v.sort_by(|a, b| a.name.cmp(&b.name));
        v.dedup_by(|a, b| a.name == b.name);
    }
    out
}

fn ident(name: &str) -> String {
    let mut s = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            s.push(c);
        } else {
            s.push('_');
        }
    }
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s.insert(0, '_');
    }
    s
}

fn module_ident(module: &str) -> String {
    ident(module.trim_end_matches(".dll"))
}

/// Pick the pattern string we want to emit for a given hit.  We prefer
/// the auto-synthesised IDA pattern at the resolved RVA (handles
/// `StringRef` entries whose database `pattern` is text, not bytes),
/// and fall back to the database pattern when `.text` was outside the
/// scanned range (rare).
fn emit_pattern(h: &PatternHit) -> Option<&str> {
    if let Some(p) = h.pattern_synth.as_deref() {
        return Some(p);
    }
    // Skip StringRef when no synth — its `pattern` field is the literal
    // string, not a byte pattern, so it would never scan-match.
    if h.resolve == "StringRef" {
        return None;
    }
    Some(h.pattern.as_str())
}

/// C++ header with one `inline constexpr` IDA-style pattern per
/// Pattern, namespaced per module.  In addition to the pattern
/// strings we emit a sibling `using <Name>_t = void(__fastcall*)(...);`
/// function-pointer typedef for every Pattern so consumers can write
/// `auto fn = reinterpret_cast<cs2::fn::client_dll::CreateMove_t>(scan(...));`
/// without re-typing the calling convention.  We don't know the real
/// argument list (this would require type recovery from IDA / a
/// debugger), so the typedef is intentionally generic
/// (`void __fastcall(void*, ...)`) and the consumer can
/// `reinterpret_cast` it to a more specific shape when they hook.
pub fn render_hpp(hits: &[PatternHit]) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk — https://cs2-sdk.com\n");
    s.push_str("// Each constant is an IDA-style byte pattern; scan it at\n");
    s.push_str("// runtime with your favourite pattern scanner.\n");
    s.push_str("#pragma once\n\n#include <string_view>\n\n");
    s.push_str("namespace pattern {\n");
    for (module, items) in grouped(hits) {
        s.push_str(&format!("    namespace {} {{\n", module_ident(&module)));
        for h in &items {
            let Some(pattern) = emit_pattern(h) else { continue };
            s.push_str(&format!(
                "        inline constexpr std::string_view {} = \"{}\";\n",
                ident(&h.name),
                pattern,
            ));
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n");
    s
}

