#pragma once

#define ICON_FA_CROSSHAIRS    "\xef\x81\x9b"
#define ICON_FA_FIRE          "\xef\x81\xad"
#define ICON_FA_USERS         "\xef\x83\x80"
#define ICON_FA_COG           "\xef\x80\x93"
#define ICON_FA_EYE           "\xef\x81\xae"
#define ICON_FA_PAINT_BRUSH   "\xef\x87\xbc"
#define ICON_FA_PLUS          "\xef\x81\xa7"
#define ICON_FA_TIMES         "\xef\x80\x8d"
#define ICON_FA_ARCHIVE       "\xef\x86\x87"
#define ICON_FA_MOUSE         "\xef\xa3\x8c"
#define ICON_FA_SKULL         "\xef\x95\x8c"
#define ICON_FA_TAG           "\xef\x80\xab"
#define ICON_FA_CLOUD         "\xef\x83\x82"
#define ICON_FA_BARS          "\xef\x83\x89"
#define ICON_FA_EDIT          "\xef\x81\x84"
#define ICON_FA_FOLDER        "\xef\x81\xbb"

#define ICON_FA_SAVE          "\xef\x83\x87"
#define ICON_FA_TRASH         "\xef\x8b\xad"
#define ICON_FA_PENCIL_ALT    "\xef\x8c\x83"
#define ICON_FA_SYNC_ALT      "\xef\x8b\xb1"
#define ICON_FA_SLIDERS_H     "\xef\x87\x9e"
#define ICON_FA_UPLOAD        "\xef\x82\x93"
#define ICON_FA_DOWNLOAD      "\xef\x80\x99"
#define ICON_FA_SHIELD_ALT    "\xef\x8e\xa1"