#pragma once
#include <SafetyHook/safetyhook.hpp>

enum ESource2ClientFrameStage : std::uint32_t
{
	/*FRAME_UNDEFINED = -1,
	FRAME_START,
	FRAME_INTERPOLATE_PHASE_START,
	FRAME_NET_UPDATE,
	FRAME_POST_DATA_UPDATE,
	FRAME_POST_ENTITY_PACKET_RECIEVED,
	FRAME_UNK1,
	FRAME_UNK2,
	FRAME_INTERPOLATE_PHASE_END,
	FRAME_HLTV_REPLAY*/
	FRAME_NET_UPDATE_POSTDATAUPDATE_START = 2,
	FRAME_NET_UPDATE_POSTDATAUPDATE_END,
	FRAME_NET_FULL_FRAME_UPDATE_ON_REMOVE,
	FRAME_RENDER_START,
	FRAME_RENDER_END,
	FRAME_NET_UPDATE_END,
	FRAME_NET_CREATION,
	FRAME_RESTORE_SERVER_STATE,
	FRAME_SIMULATE_END
};

inline SafetyHookInline FrameStageNotify_o{};
auto __fastcall Hook_FrameStageNotify( void* pSource2Client, int nFrameStage ) -> void;