//! Single-include amalgamation header(s).
//!
//! For internal cheats it's enormously useful to have one file you can
//! `#include` (or one Rust module you can copy in) that pulls in
//! offsets + interfaces + netvars + patterns + the SDK macros all at
//! once.
//!
//! This module emits `cs2.hpp` — the single-include C++ amalgamation.
//! It is *idempotent*: it only re-exports what other emitters in this
//! run produced, it doesn't duplicate any data.
//!
//! ## Design choice: `#include`s vs amalgamation
//!
//! We deliberately use `#include` rather than concatenating every file's
//! contents into one mega-file. That keeps:
//!
//! 1. compile times low (the user only pays for what they touch),
//! 2. error messages pointing at the right file, and
//! 3. diffs between two builds clean.

/// Render a single-include C++ header.
///
/// `sdk_modules` is the list of module file stems that the SDK class
/// emitter wrote (e.g. `["client_dll", "engine2_dll"]`).
pub fn render_hpp(sdk_modules: &[String], build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk - https://cs2-sdk.com\n");
    s.push_str("//\n");
    s.push_str("// Single-include amalgamation header for CS2 internal cheats.\n");
    s.push_str("//\n");
    s.push_str("// Add the dump's `include/` to your include path and:\n");
    s.push_str("//\n");
    s.push_str("//     #include <cs2.hpp>\n\n");
    s.push_str("#pragma once\n\n");
    if let Some(bn) = build_number {
        s.push_str(&format!("inline constexpr unsigned int CS2_BUILD = {bn};\n\n"));
    }
    s.push_str("#include \"macros.hpp\"\n\n");
    s.push_str("// Per-module schema classes\n");

    // Editor/tool-only modules a runtime consumer (cheat) never needs. Their
    // schemas pull in large editor-only type graphs (and Windows-macro enum
    // name collisions like RELATIVE/ABSOLUTE) that don't belong in the runtime
    // amalgamation, so they're omitted here. The per-module headers are still
    // written to schemas/ for anyone who wants them directly.
    const EDITOR_MODULES: &[&str] = &[
        "assetbrowser_dll",
        "assetpreview_dll",
        "assetrename_dll",
        "met_dll",
        "modtools_dll",
        "resourcecompiler_dll",
    ];

    let mut ordered_modules: Vec<String> = sdk_modules
        .iter()
        .filter(|m| !EDITOR_MODULES.contains(&m.as_str()))
        .cloned()
        .collect();
    // client must precede server (server uses client-owned bases).
    if ordered_modules.contains(&"server_dll".to_string())
        && ordered_modules.contains(&"client_dll".to_string())
    {
        ordered_modules.retain(|m| m != "client_dll");
        if let Some(pos) = ordered_modules.iter().position(|m| m == "server_dll") {
            ordered_modules.insert(pos, "client_dll".to_string());
        } else {
            ordered_modules.insert(0, "client_dll".to_string());
        }
    }

    for m in ordered_modules {
        s.push_str(&format!("#include \"schemas/{}.hpp\"\n", m));
    }
    s.push('\n');
    s.push_str("#include \"offsets/offsets.hpp\"\n");
    s.push_str("#include \"interfaces/interfaces.hpp\"\n");
    s.push_str("#include \"buttons.hpp\"\n");
    s.push_str("#include \"protobufs/protobufs.hpp\"\n");
    s.push_str("#include \"patterns/patterns.hpp\"\n");
    s.push('\n');
    s.push_str("#include \"impl/entity_system.hpp\"\n");
    s
}
