//! Entity-system traversal helpers — implementation header under `impl/`.

use std::fmt::Write;

use crate::analysis::{OffsetMap, SchemaMap};

pub fn render_hpp(
    _offsets: &OffsetMap,
    build_number: Option<u32>,
    _schemas: &SchemaMap,
) -> String {
    let mut s = String::new();

    writeln!(s, "// Generated by cs2-sdk — https://cs2-sdk.com").ok();
    writeln!(s, "#pragma once").ok();
    writeln!(s).ok();
    writeln!(s, "#include <cstdint>").ok();
    writeln!(s, "#include <windows.h>").ok();
    writeln!(s, "#include \"../offsets/offsets.hpp\"").ok();
    writeln!(s, "#include \"../schemas/client_dll.hpp\"").ok();
    writeln!(s).ok();

    if let Some(bn) = build_number {
        writeln!(s, "namespace entity {{ inline constexpr std::uint32_t CS2_BUILD = {bn}; }}\n").ok();
    }

    writeln!(s, "struct CGameEntitySystem {{").ok();

    // CGameEntitySystem layout constants — not exposed by the schema.
    writeln!(s, "    // Offset of the entity-list chunk-pointer array within CGameEntitySystem.").ok();
    writeln!(s, "    static constexpr std::size_t kEntityListOffset = 0x10;").ok();
    // Each chunk holds 512 CEntityIdentity objects laid out contiguously.
    // sizeof(CEntityIdentity) = 0x70 (last schema field m_pNextByClass at 0x68 + 8 bytes).
    writeln!(s, "    static constexpr std::size_t kIdentityStride    = 0x70;").ok();
    writeln!(s, "    static constexpr int          kChunkSize         = 512;").ok();
    writeln!(s, "    static constexpr int          kMaxEntities       = 32768;").ok();
    writeln!(s).ok();

    writeln!(s, "    static int GetHighestEntityIndex() noexcept {{").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return 0;").ok();
    writeln!(s, "        auto es = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);").ok();
    writeln!(s, "        if (!es) return 0;").ok();
    writeln!(s, "        return *reinterpret_cast<int*>(es + offsets::client::GameEntitySystem_highestEntityIndex);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    static client::CCSPlayerController* GetLocalPlayer() noexcept {{").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<client::CCSPlayerController**>(client + offsets::client::LocalPlayerController);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    static client::CEntityIdentity* GetIdentityByIndex(int index) noexcept {{").ok();
    writeln!(s, "        if (index < 0) return nullptr;").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        auto entity_system = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);").ok();
    writeln!(s, "        if (!entity_system) return nullptr;").ok();
    writeln!(s, "        auto chunk = *reinterpret_cast<uintptr_t*>(entity_system + kEntityListOffset + static_cast<std::size_t>(index / kChunkSize) * 8);").ok();
    writeln!(s, "        if (!chunk) return nullptr;").ok();
    writeln!(s, "        return reinterpret_cast<client::CEntityIdentity*>(chunk + static_cast<std::size_t>(index % kChunkSize) * kIdentityStride);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    // m_pEntity (the CEntityInstance* this identity belongs to) is the first
    // field of CEntityIdentity at offset 0x0, before the schema-exported area.
    writeln!(s, "    static void* GetEntityByIndex(int index) noexcept {{").ok();
    writeln!(s, "        if (index < 0 || index >= kMaxEntities) return nullptr;").ok();
    writeln!(s, "        auto* identity = GetIdentityByIndex(index);").ok();
    writeln!(s, "        if (!identity) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<void**>(identity); // m_pEntity at offset 0x0").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    static const char* GetDesignerName(int index) noexcept {{").ok();
    writeln!(s, "        auto* identity = GetIdentityByIndex(index);").ok();
    writeln!(s, "        if (!identity || !GetEntityByIndex(index)) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<const char**>(&identity->m_designerName());").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    static bool IsPlayerPawn(uint16_t entity_index) noexcept {{").ok();
    writeln!(s, "        for (int i = 1; i <= 64; ++i) {{").ok();
    writeln!(s, "            auto* controller = reinterpret_cast<client::CCSPlayerController*>(GetEntityByIndex(i));").ok();
    writeln!(s, "            if (!controller || reinterpret_cast<uintptr_t>(controller) <= 0x10000) continue;").ok();
    writeln!(s, "            if (controller->m_iTeamNum() != 2 && controller->m_iTeamNum() != 3) continue;").ok();
    writeln!(s, "            if (controller->m_hPawn().GetIndex() == entity_index) return true;").ok();
    writeln!(s, "        }}").ok();
    writeln!(s, "        return false;").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "}};").ok();
    writeln!(s).ok();

    s
}
