//! Combined interfaces header.
//!
//! Emits `interfaces/interfaces.hpp` with everything under one `ifc::` namespace:
//!
//! - `ifc::<module>::<Class>` — abstract C++ structs whose pure-virtuals are
//!   declared in vtable-slot order so layout mirrors the game's.
//! - `ifc::<ShortName>()` — zero-argument top-level accessors that resolve the
//!   module via GetModuleHandleA and return a ready-to-use typed pointer.
//!
//! Usage:
//! ```cpp
//! ifc::InputSystem()->SetRelativeMouseMode(false);
//! ifc::EnginePVSManager()->SetPvsEnabled(false);
//! ifc::MaterialSystem2()->...;
//! ifc::LocalPlayerController()->m_iTeamNum();
//! ```

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::analysis::InterfaceMap;

use super::ident::{sanitize_ident, slugify, type_ident};

pub struct Method {
    pub index: usize,
    /// Pattern-recovered name for this slot, when known.
    pub name: Option<String>,
}

pub struct IfaceClass {
    pub module: String,
    pub iface_name: String,
    pub rtti_class: Option<String>,
    pub methods: Vec<Method>,
    /// True for classes discovered via pattern + RTTI walk rather than
    /// CreateInterface registration. Affects rendering only at the struct
    /// banner — `iface:` is shown as empty.
    pub manual: bool,
}


struct Curated {
    ret: &'static str,
    name: &'static str,
    params: &'static [&'static str],
}

fn curated(module: &str, class: &str, index: usize) -> Option<Curated> {
    match (module, class, index) {
        ("inputsystem.dll", "CInputSystem",      76) => Some(Curated { ret: "void",  name: "SetRelativeMouseMode", params: &["bool"] }),
        ("panorama.dll",    "CPanoramaUIEngine", 13) => Some(Curated { ret: "void*", name: "GetUIEngine",          params: &[]       }),
        ("engine2.dll",     "CEnginePVSManager",  6) => Some(Curated { ret: "void",  name: "SetPvsEnabled",        params: &["bool"] }),
        _ => None,
    }
}


fn module_ns(module: &str) -> String {
    slugify(module.trim_end_matches(".dll"))
}

fn class_ns(c: &IfaceClass) -> String {
    c.rtti_class.as_deref().map(sanitize_ident).unwrap_or_else(|| type_ident(&c.iface_name))
}

pub fn render_hpp(
    _interfaces: &InterfaceMap,
    classes: &[IfaceClass],
    build_number: Option<u32>,
) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk - https://cs2-sdk.com\n");
    s.push_str("//\n");
    s.push_str("// CS2 interfaces — typed vtable structs in `ifc::<module>::<Class>`.\n");
    s.push_str("// Resolved singleton RVAs are exposed as constants in offsets.hpp\n");
    s.push_str("// (with a `p` prefix when one runtime dereference is needed). Build\n");
    s.push_str("// the typed pointer at the call site or in a project-local wrapper:\n");
    s.push_str("//\n");
    s.push_str("//   auto* is = reinterpret_cast<ifc::inputsystem::CInputSystem*>(\n");
    s.push_str("//       (std::uintptr_t)GetModuleHandleA(\"inputsystem.dll\") + offsets::inputsystem::InputSystemVersion001\n");
    s.push_str("//   );\n");
    s.push_str("//   is->SetRelativeMouseMode(false);\n");
    s.push_str("//\n");
    s.push_str("// NOTE: only the primary vtable (*(void**)instance) is walked. Classes\n");
    s.push_str("// reached solely via a secondary vtable (multiple inheritance) are not\n");
    s.push_str("// covered and may be missing slots.\n");
    s.push_str("\n#pragma once\n");
    s.push_str("#include <cstdint>\n\n");

    if let Some(bn) = build_number {
        writeln!(s, "namespace ifc {{ inline constexpr std::uint32_t CS2_BUILD = {bn}; }}\n").ok();
    }

    // --- ifc::module::Class structs ----------------------------------------
    let mut sorted: Vec<&IfaceClass> = classes.iter().collect();
    sorted.sort_by(|a, b| (a.module.as_str(), a.iface_name.as_str()).cmp(&(b.module.as_str(), b.iface_name.as_str())));

    let mut grouped: BTreeMap<String, BTreeMap<String, (&IfaceClass, Vec<String>)>> = BTreeMap::new();
    for c in &sorted {
        let entry = grouped.entry(c.module.clone()).or_default()
            .entry(class_ns(c)).or_insert_with(|| (*c, Vec::new()));
        if !c.manual {
            entry.1.push(c.iface_name.clone());
        }
    }

    s.push_str("namespace ifc {\n\n");
    for (module, ns_map) in &grouped {
        let mns = module_ns(module);
        writeln!(s, "    namespace {} {{", mns).ok();
        for (cns, (rep, ifaces)) in ns_map {
            writeln!(s, "        // {} (iface: {}) | {} methods", cns, ifaces.join(", "), rep.methods.len()).ok();
            writeln!(s, "        struct {} {{", cns).ok();

            for m in &rep.methods {
                if let Some(cur) = curated(module, cns, m.index) {
                    let params = cur.params.iter().enumerate()
                        .map(|(i, t)| format!("{} a{}", t, i))
                        .collect::<Vec<_>>().join(", ");
                    writeln!(s, "            virtual {} {}({}) = 0; // slot {}", cur.ret, cur.name, params, m.index).ok();
                } else if let Some(name) = m.name.as_deref() {
                    // Slot identified via Pattern-RVA cross-reference; args unknown.
                    writeln!(s, "            virtual void {}() = 0; // slot {} (name recovered, args unverified)", sanitize_ident(name), m.index).ok();
                } else {
                    writeln!(s, "            virtual void method_{}() = 0;", m.index).ok();
                }
            }
            for m in &rep.methods {
                if let Some(cur) = curated(module, cns, m.index) {
                    writeln!(
                        s,
                        "            void* p{}() {{ return (*reinterpret_cast<void***>(this))[{}]; }}",
                        cur.name, m.index
                    ).ok();
                }
            }
            writeln!(s, "        }};").ok();
        }
        writeln!(s, "    }} // namespace {}\n", mns).ok();
    }
    s.push_str("} // namespace ifc\n");
    s
}
