//! Netvar / `MNetworkVarNames` extractor + emitter.
//!
//! # Background
//!
//! Source 2 marks every networked field on every entity with a
//! `MNetworkVarNames(<schema_name>, <type_name>)` metadata entry on its
//! enclosing class. The schema dump already captures this metadata —
//! this emitter just splits it out into its own file so internals don't
//! have to dig through the (large) schema dump to find network-relevant
//! fields.
//!
//! # Output
//!
//! Each call writes:
//!
//! - `netvars.json` — `{ class_name: { field_name: { offset, type } } }`
//! - `netvars.hpp`  — `inline constexpr std::ptrdiff_t` per field, namespaced
//! - `netvars.cs`   — same as `.hpp` for C# consumers
//!
//! The grouping is by class, not by module, because internal cheats
//! generally lookup netvars by `(class, field)` pair regardless of which
//! DLL the class came from.

use std::collections::BTreeMap;
use std::fmt::Write;

use serde_json::json;

use crate::analysis::{ClassMetadata, SchemaMap};

use super::ident::type_ident;

/// Extracted view of one networked field.
#[derive(Debug, Clone)]
pub struct NetVar {
    pub class: String,
    pub field: String,
    pub offset: i32,
    pub type_name: String,
}

/// Walk the schema and pull out every field that has a matching
/// `MNetworkVarNames` metadata entry.
///
/// The metadata is keyed by *field name* and applies to the same class
/// — the schema parser already attached the metadata list to each class,
/// so all we have to do is filter and zip with the matching field.
pub fn extract(schemas: &SchemaMap) -> Vec<NetVar> {
    let mut out = Vec::new();
    for (_, (classes, _)) in schemas {
        for class in classes {
            for meta in &class.metadata {
                let ClassMetadata::NetworkVarNames { name, type_name } = meta else {
                    continue;
                };
                let Some(field) = class.fields.iter().find(|f| &f.name == name) else {
                    // Schema occasionally lists netvar metadata without a
                    // matching real field (compile-time metadata only).
                    // We skip those — they have no usable offset.
                    continue;
                };
                out.push(NetVar {
                    class: class.name.clone(),
                    field: name.clone(),
                    offset: field.offset,
                    type_name: type_name.clone(),
                });
            }
        }
    }
    out.sort_by(|a, b| (&a.class, &a.field).cmp(&(&b.class, &b.field)));
    out
}

/// Group [`NetVar`]s by class for emitters that nest per-class.
fn grouped(netvars: &[NetVar]) -> BTreeMap<&str, Vec<&NetVar>> {
    let mut out: BTreeMap<&str, Vec<&NetVar>> = BTreeMap::new();
    for n in netvars {
        out.entry(n.class.as_str()).or_default().push(n);
    }
    out
}

/// Emit a JSON document keyed by class then field.
pub fn render_json(netvars: &[NetVar]) -> String {
    let mut by_class: BTreeMap<&str, BTreeMap<&str, serde_json::Value>> = BTreeMap::new();
    for n in netvars {
        by_class.entry(n.class.as_str()).or_default().insert(
            n.field.as_str(),
            json!({ "offset": n.offset, "type": n.type_name }),
        );
    }
    serde_json::to_string_pretty(&by_class).unwrap_or_else(|_| "{}".into())
}

/// Emit a C++ header: `sdk::netvars::<class>::<field>`.
pub fn render_hpp(netvars: &[NetVar], build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk - https://cs2-sdk.com\n");
    s.push_str("#pragma once\n\n");
    s.push_str("#include <cstddef>\n#include <cstdint>\n\n");
    if let Some(bn) = build_number {
        writeln!(s, "namespace netvar {{ inline constexpr std::uint32_t CS2_BUILD = {bn}; }}\n").ok();
    }
    s.push_str("namespace netvar {\n\n");
    for (class, fields) in grouped(netvars) {
        writeln!(s, "    namespace {} {{", type_ident(class)).ok();
        for n in fields {
            writeln!(
                s,
                "        inline constexpr std::ptrdiff_t {:<48} = {:#X}; // {}",
                n.field, n.offset, n.type_name,
            )
            .ok();
        }
        writeln!(s, "    }} // namespace {}\n", type_ident(class)).ok();
    }
    s.push_str("} // namespace netvar\n");
    s
}

