//! C++ SDK header emitter — turns the raw schema dump into ready-to-use
//! classes with `SCHEMA_FIELD` accessors.
//!
//! # What this produces
//!
//! For each schema module (e.g. `client.dll`) we emit a single header
//! `sdk/<module>.hpp` whose contents look like this:
//!
//! ```cpp
//! // Generated by cs2-sdk - https://cs2-sdk.com
//! //
//! // build_number: 14152
//! // generated_at: 2026-04-21T22:16:38+01:00
//! //
//! // Drop this header into your internal cheat and call schema fields with:
//! //
//! //     auto* pawn = some_pawn_pointer;
//! //     int  hp    = pawn->m_iHealth();
//! //     pawn->m_iHealth() = 100;
//! //
//! // The macros below produce inline accessors that compute
//! //     reinterpret_cast<T&>(*((std::byte*)this + offset))
//! // so they are zero-overhead in release builds.
//!
//! #pragma once
//! #include "cs2sdk_macros.hpp"
//!
//! namespace sdk::client {
//!     class C_BasePlayerPawn;
//!
//!     class C_CSPlayerPawn : public C_BasePlayerPawn {
//!     public:
//!         SCHEMA_FIELD(int32_t,  m_iHealth,        0x344)
//!         SCHEMA_FIELD(QAngle,   m_angEyeAngles,   0x1334)
//!     };
//! }
//! ```
//!
//! # Why this is in a separate emitter
//!
//! The existing `output::schemas` emitter produces `constexpr offset =
//! 0xABC;` constants, which is what the original cs2-dumper consumers
//! expect. This emitter is *additive* — it leaves the original output
//! untouched and adds a parallel `sdk/` tree of header files that are
//! more ergonomic for cheat developers.
//!
//! # Type translation
//!
//! Schema type names (`"int32"`, `"CHandle< C_BaseEntity >"`,
//! `"CUtlVector< Vector >"`, ...) are mapped to their canonical C++
//! equivalents through [`map_schema_type`]. Anything we don't recognise
//! is forwarded as-is wrapped in a `using` so the file still compiles.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::analysis::{Class, Enum, SchemaMap};

use super::ident::{slugify, type_ident};

/// Render every schema module into its own `*.hpp` SDK file.
///
/// Returns a list of `(file_name, file_contents)` pairs. The file name is
/// the module slug (e.g. `client_dll.hpp`) and the contents are the full
/// header text including the build banner.
pub fn render_module_headers(
    schemas: &SchemaMap,
    buttons: &BTreeMap<String, u64>,
    build_number: Option<u32>,
    timestamp: &str,
) -> Vec<(String, String)> {
    let mut out = Vec::with_capacity(schemas.len());
    let mut module_data: Vec<(String, String, Vec<Class>, Vec<Enum>)> = Vec::with_capacity(schemas.len());
    let mut type_namespace_map: BTreeMap<String, String> = BTreeMap::new();
    let canonical_type_namespace_map = get_type_namespace_map();
    // Cross-module dedup: a schema class registered in two modules
    // (common for shared bases like CBaseEntity in both client.dll and
    // server.dll) is only emitted in the FIRST module that contained it.
    // Without this we get conflicting types across `sdk::client::` and
    // `sdk::server::` for what is logically the same class.
    let mut seen_classes: BTreeSet<String> = BTreeSet::new();
    let mut seen_enums: BTreeSet<String> = BTreeSet::new();

    // First pass: build type_namespace_map and apply dedup
    for (module, (classes, enums)) in schemas {
        let ns = slugify(module.trim_end_matches(".dll"));

        // Build filtered classes honoring canonical ownership: if a class has a
        // canonical owner (from get_type_namespace_map) we only emit it in that
        // owner module. Otherwise, the first module encountered claims it.
        let mut filtered_classes: Vec<Class> = Vec::new();
        for c in classes {
            let class_name = sanitize_class_name(&c.name);
            if let Some(&owner) = canonical_type_namespace_map.get(class_name.as_str()) {
                // Known canonical owner: only emit when current ns matches owner
                if owner == ns {
                    if seen_classes.insert(class_name.clone()) {
                        filtered_classes.push(c.clone());
                    }
                } else {
                    // Skip emitting here; owner module will emit
                    // but ensure we record the namespace mapping below
                    type_namespace_map.insert(class_name.clone(), owner.to_string());
                }
            } else {
                // No canonical owner: first occurrence wins
                if seen_classes.insert(class_name.clone()) {
                    filtered_classes.push(c.clone());
                    type_namespace_map.entry(class_name.clone()).or_insert_with(|| ns.clone());
                }
            }
        }

        let mut filtered_enums: Vec<Enum> = Vec::new();
        for e in enums {
            let enum_name = type_ident(&e.name);
            if let Some(&owner) = canonical_type_namespace_map.get(enum_name.as_str()) {
                type_namespace_map.insert(enum_name.clone(), owner.to_string());
            } else {
                if seen_enums.insert(enum_name.clone()) {
                    filtered_enums.push(e.clone());
                    type_namespace_map.entry(enum_name.clone()).or_insert_with(|| ns.clone());
                }
            }

            let alias_name = sanitize_class_name(&e.name);
            if let Some(&owner) = canonical_type_namespace_map.get(alias_name.as_str()) {
                type_namespace_map.insert(alias_name, owner.to_string());
            } else {
                type_namespace_map.entry(alias_name).or_insert_with(|| ns.clone());
            }
        }

        let file_name = format!("{}.hpp", slugify(module));
        module_data.push((file_name, module.clone(), filtered_classes, filtered_enums));
    }

    // Compute module include ordering once so it's deterministic and
    // we can inspect it while debugging header cycles.
    let module_index_map = module_include_index_map(&type_namespace_map, schemas);

    for (file_name, module, filtered_classes, filtered_enums) in module_data {
        let body = render_one_module(
            &module,
            &filtered_classes,
            &filtered_enums,
            buttons,
            build_number,
            timestamp,
            &type_namespace_map,
            &module_index_map,
        );
        out.push((file_name, body));
    }
    out
}


/// Build a deterministic index map for module include ordering.
/// We compute inter-module dependencies and then topologically sort modules
/// so headers only include dependency headers that come earlier in the order.
fn module_include_index_map(
    type_namespace_map: &BTreeMap<String, String>,
    schemas: &SchemaMap,
) -> BTreeMap<String, usize> {
    use std::collections::{HashMap, VecDeque};

    // Collect all modules
    let mut modules: BTreeSet<String> = BTreeSet::new();
    for (module, _) in schemas {
        modules.insert(slugify(module.trim_end_matches(".dll")).to_string());
    }

    // Build dependency graph: module -> set of modules it depends on
    let mut deps: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for (module, (classes, _)) in schemas {
        let ns = slugify(module.trim_end_matches(".dll"));
        let mut sdeps: BTreeSet<String> = BTreeSet::new();
        for c in classes {
            if let Some(parent) = &c.parent_name {
                let sanitized_parent = sanitize_class_name(parent);
                if let Some(owner_ns) = type_namespace_map.get(&sanitized_parent) {
                    if owner_ns != &ns {
                        sdeps.insert(owner_ns.clone());
                    }
                }
            }


        }
        deps.insert(ns.clone(), sdeps);
    }

    // Kahn's algorithm for topological sort of modules
    // Build adjacency list where edge dep -> module (dep must come before module)
    let mut in_degree: HashMap<String, usize> = HashMap::new();
    let mut adj: HashMap<String, Vec<String>> = HashMap::new();
    for m in &modules {
        in_degree.insert(m.clone(), 0);
    }

    for (module, sdeps) in &deps {
        // module depends on each dep; increment module's in-degree
        let cnt = in_degree.entry(module.clone()).or_insert(0);
        *cnt += sdeps.len();
        for dep in sdeps {
            adj.entry(dep.clone()).or_insert_with(Vec::new).push(module.clone());
        }
    }

    let mut q: VecDeque<String> = in_degree
        .iter()
        .filter_map(|(k, v)| if *v == 0 { Some(k.clone()) } else { None })
        .collect();

    let mut order: Vec<String> = Vec::new();
    while let Some(m) = q.pop_front() {
        order.push(m.clone());
        if let Some(children) = adj.get(&m) {
            for child in children {
                if let Some(cnt) = in_degree.get_mut(child) {
                    *cnt = cnt.saturating_sub(1);
                    if *cnt == 0 {
                        q.push_back(child.clone());
                    }
                }
            }
        }
    }

    // If cycles exist, append remaining modules deterministically.
    if order.len() < modules.len() {
        // Remaining modules set
        let remaining_set: BTreeSet<String> = modules.into_iter().filter(|m| !order.contains(m)).collect();

        // Build subgraph of dependencies restricted to the remaining modules
        let mut sub_deps: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
        for (module, sdeps) in &deps {
            if remaining_set.contains(module) {
                let mut filtered: BTreeSet<String> = BTreeSet::new();
                for d in sdeps {
                    if remaining_set.contains(d) {
                        filtered.insert(d.clone());
                    }
                }
                sub_deps.insert(module.clone(), filtered);
            }
        }

        // Try Kahn's algorithm on the restricted subgraph to produce a partial order
        use std::collections::VecDeque;
        let mut in_deg: BTreeMap<String, usize> = BTreeMap::new();
        let mut adj: BTreeMap<String, Vec<String>> = BTreeMap::new();
        for m in &remaining_set {
            in_deg.insert(m.clone(), 0);
        }
        for (m, sdeps) in &sub_deps {
            let cnt = in_deg.entry(m.clone()).or_insert(0);
            *cnt += sdeps.len();
            for dep in sdeps {
                adj.entry(dep.clone()).or_insert_with(Vec::new).push(m.clone());
            }
        }

        let mut q: VecDeque<String> = in_deg.iter().filter_map(|(k, v)| if *v == 0 { Some(k.clone()) } else { None }).collect();
        let mut sub_order: Vec<String> = Vec::new();
        while let Some(m) = q.pop_front() {
            sub_order.push(m.clone());
            if let Some(children) = adj.get(&m) {
                for child in children {
                    if let Some(cnt) = in_deg.get_mut(child) {
                        *cnt = cnt.saturating_sub(1);
                        if *cnt == 0 {
                            q.push_back(child.clone());
                        }
                    }
                }
            }
        }

        // Any modules not included by the sub-order are in a cycle. Append
        // them deterministically with a small priority favoring server.
        let mut remaining_list: Vec<String> = remaining_set.into_iter().filter(|m| !sub_order.contains(m)).collect();
        let priority = |m: &str| {
            match m {
                "server" => 0,
                "client" => 1,
                _ => 2,
            }
        };
        remaining_list.sort_by_key(|m| (priority(m.as_str()), m.clone()));

        // Append the sub_order first, then the remaining_list
        for m in sub_order.into_iter() {
            order.push(m);
        }
        for m in remaining_list.into_iter() {
            order.push(m);
        }
    }

    // Build index map
    let mut map = BTreeMap::new();
    for (i, m) in order.into_iter().enumerate() {
        map.insert(m, i);
    }
    map
}

/// Topologically sort classes so that base classes are defined before derived classes.
/// Classes with no parent or whose parent is not in the list come first.
/// This prevents "base class undefined" errors during compilation.
fn topological_sort_classes(classes: &[Class]) -> Vec<&Class> {
    use std::collections::{HashMap, VecDeque};

    // Build a map of class name -> class reference
    let class_map: HashMap<String, &Class> = classes
        .iter()
        .map(|c| (sanitize_class_name(&c.name), c))
        .collect();

    // Build dependency graph: class -> set of classes that depend on it (children)
    let mut children: HashMap<String, Vec<String>> = HashMap::new();
    let mut parent_count: HashMap<String, usize> = HashMap::new();

    for c in classes {
        let sanitized_name = sanitize_class_name(&c.name);
        parent_count.entry(sanitized_name.clone()).or_insert(0);

        if let Some(parent) = &c.parent_name {
            let sanitized_parent = sanitize_class_name(parent);

            // Only count as a dependency if the parent exists in this module
            if class_map.contains_key(&sanitized_parent) {
                children
                    .entry(sanitized_parent.clone())
                    .or_insert_with(Vec::new)
                    .push(sanitized_name.clone());
                *parent_count.entry(sanitized_name).or_insert(0) += 1;
            }
        }
    }

    // Kahn's algorithm for topological sort
    let mut queue: VecDeque<String> = parent_count
        .iter()
        .filter(|(_, count)| **count == 0)
        .map(|(name, _)| name.clone())
        .collect();

    let mut sorted = Vec::with_capacity(classes.len());

    while let Some(class_name) = queue.pop_front() {
        if let Some(&class_ref) = class_map.get(&class_name) {
            sorted.push(class_ref);
        }

        // Decrease parent count for all children
        if let Some(child_list) = children.get(&class_name) {
            for child in child_list {
                if let Some(count) = parent_count.get_mut(child) {
                    *count -= 1;
                    if *count == 0 {
                        queue.push_back(child.clone());
                    }
                }
            }
        }
    }

    // If there are cycles or classes we missed, append them at the end
    if sorted.len() < classes.len() {
        for c in classes {
            let sanitized_name = sanitize_class_name(&c.name);
            if !sorted.iter().any(|&sc| sanitize_class_name(&sc.name) == sanitized_name) {
                sorted.push(c);
            }
        }
    }

    sorted
}

/// Map of types to their proper SDK namespaces.
/// Used to emit types in their correct nested namespace scope.
fn get_type_namespace_map() -> BTreeMap<&'static str, &'static str> {
    let mut map = BTreeMap::new();

    // resourcesystem types
    map.insert("InfoForResourceTypeIPulseGraphDef", "resourcesystem");
    map.insert("InfoForResourceTypeCModel", "resourcesystem");
    map.insert("InfoForResourceTypeCRenderMesh", "resourcesystem");
    map.insert("InfoForResourceTypeCCompositeMaterialKit", "resourcesystem");
    map.insert("InfoForResourceTypeCCompositeMaterial", "resourcesystem");
    map.insert("InfoForResourceTypeCNmSkeleton", "resourcesystem");
    map.insert("InfoForResourceTypeIMaterial2", "resourcesystem");
    map.insert("InfoForResourceTypeIParticleSystemDefinition", "resourcesystem");
    map.insert("InfoForResourceTypeIParticleSnapshot", "resourcesystem");
    map.insert("InfoForResourceTypeCNmGraphDefinition", "resourcesystem");
    map.insert("InfoForResourceTypeCNmClip", "resourcesystem");
    map.insert("InfoForResourceTypeCEntityLump", "resourcesystem");
    map.insert("InfoForResourceTypeCChoreoSceneResource", "resourcesystem");
    map.insert("InfoForResourceTypeCPostProcessingResource", "resourcesystem");
    map.insert("InfoForResourceTypeCPhysAggregateData", "resourcesystem");
    map.insert("InfoForResourceTypeCAnimationGroup", "resourcesystem");
    map.insert("InfoForResourceTypeCSequenceGroupData", "resourcesystem");
    map.insert("InfoForResourceTypeCTextureBase", "resourcesystem");
    map.insert("InfoForResourceTypeCAnimData", "resourcesystem");
    map.insert("InfoForResourceTypeCVoiceContainerBase", "resourcesystem");
    map.insert("InfoForResourceTypeCVMixListResource", "resourcesystem");
    map.insert("AABB_t", "resourcesystem");
    map.insert("PackedAABB_t", "resourcesystem");

    // schemasystem types
    map.insert("fieldtype_t", "schemasystem");

    // rendersystemdx11 types
    map.insert("RenderPrimitiveType_t", "rendersystemdx11");

    // particles types
    map.insert("ParticleAttributeIndex_t", "particles");
    map.insert("ParticleIndex_t", "particles");
    map.insert("ParticleModelType_t", "particles");
    map.insert("ParticleNamedValueSource_t", "particles");
    map.insert("ParticleColorBlendType_t", "particles");
    map.insert("ParticleColorBlendMode_t", "particles");
    map.insert("ParticleDirectionNoiseType_t", "particles");
    map.insert("ParticleSetMethod_t", "particles");
    map.insert("IParticleCollection", "particles");

    // server types
    map.insert("CRangeFloat", "server");
    map.insert("CLogicalEntity", "server");
    map.insert("CBaseFilter", "server");
    map.insert("CBaseAnimGraph", "server");
    map.insert("CBaseProp", "server");
    map.insert("CServerOnlyModelEntity", "server");
    map.insert("CEntityComponent", "server");
    map.insert("CPathNode", "server");
    map.insert("CAttributeManager", "server");
    map.insert("CPlayerPawnComponent", "server");
    map.insert("CPlayerControllerComponent", "server");
    map.insert("CSkeletonAnimationController", "server");
    map.insert("CBaseAnimGraphDestructibleParts_GraphController", "server");
    map.insert("CBaseAnimGraphVariationUserData", "server");
    map.insert("CBasePropDoor", "server");
    // Canonical owner overrides for classes that are conceptually client-side
    // but occasionally appear in multiple module schema dumps. Ensure these
    // are emitted in the client module so server headers can reference them
    // as ::sdk::client::Type.
    map.insert("CPathSimple", "client");
    map.insert("CPathQueryComponent", "client");
    map.insert("CPathWithDynamicNodes", "client");
    map.insert("CPathMover", "client");

    // vphysics2 types
    map.insert("RnSphereDesc_t", "vphysics2");
    map.insert("RnCapsuleDesc_t", "vphysics2");
    map.insert("RnHullDesc_t", "vphysics2");
    map.insert("RnMeshDesc_t", "vphysics2");
    map.insert("RnSoftbodyParticle_t", "vphysics2");
    map.insert("RnSoftbodySpring_t", "vphysics2");
    map.insert("RnSoftbodyCapsule_t", "vphysics2");

    map
}

/// Render a tiny shared header (`cs2sdk_macros.hpp`) that defines the
/// `SCHEMA_FIELD` macro family the generated headers depend on.
///
/// We emit this once instead of repeating the macros at the top of every
/// header.
pub fn render_macros_header() -> String {
    include_str!("macros_base.hpp").to_string()
}

fn render_one_module(
    module: &str,
    classes: &[Class],
    enums: &[Enum],
    buttons: &BTreeMap<String, u64>,
    build_number: Option<u32>,
    timestamp: &str,
    type_namespace_map: &BTreeMap<String, String>,
    module_index_map: &BTreeMap<String, usize>,
) -> String {
    let ns = slugify(module.trim_end_matches(".dll"));
    let mut s = String::with_capacity(64 * 1024);

    write_banner(&mut s, module, classes.len(), enums.len(), build_number, timestamp);
    s.push_str("#pragma once\n");
    // schemas/<module>.hpp → ../macros.hpp at the include root
    s.push_str("#include \"../macros.hpp\"\n\n");

    // Scan all classes in this module (before filtering) to find cross-module base dependencies.
    // We build two sets: `parent_deps` for classes whose parent is in another module
    // (these must be included unconditionally because inheritance requires the base
    // class definition), and `other_deps` for cross-module references discovered in
    // field types (these can be included conditionally based on module order).
    let mut parent_deps: BTreeSet<String> = BTreeSet::new();
    let other_deps: BTreeSet<String> = BTreeSet::new();
    for c in classes {
        if let Some(parent_name) = &c.parent_name {
            let sanitized_parent = sanitize_class_name(parent_name);
            // Look up the parent's module ownership
            if let Some(owner_ns) = type_namespace_map.get(&sanitized_parent) {
                if owner_ns != &ns {
                    parent_deps.insert(owner_ns.clone());
                }
            }
        }


    }

    // Emit includes. Parent dependencies are inheritance requirements, so they
    // must be included unconditionally for standalone header compilation.
    // Other dependencies are still ordered to reduce cycle pressure.
    let my_index = module_index_map.get(&ns).cloned().unwrap_or_default();

    for dep in &parent_deps {
        writeln!(s, "#include \"{}_dll.hpp\"", dep).ok();
    }

    for dep in other_deps.difference(&parent_deps) {
        // Include non-parent dependencies only if they appear earlier in the
        // global module ordering. This avoids mutual includes between modules
        // while keeping inheritance includes unconditional.
        if let Some(&dep_index) = module_index_map.get(dep) {
            if dep_index < my_index {
                writeln!(s, "#include \"{}_dll.hpp\"", dep).ok();
            }
        } else {
            // Unknown module index: be conservative and include it.
            writeln!(s, "#include \"{}_dll.hpp\"", dep).ok();
        }
    }

    if !parent_deps.is_empty() || !other_deps.is_empty() {
        s.push('\n');
    }

    writeln!(s, "namespace {} {{", ns).ok();
    writeln!(s).ok();

    // CS2_BUILD constant removed from per-module files — the running
    // build number lives in `manifest.json` and `cs2.hpp` only.
    let _ = build_number;

    // Add buttons enum for client.dll
    if module == "client.dll" && !buttons.is_empty() {
        writeln!(s, "    enum class InputButton : std::uint64_t {{").ok();
        for (name, value) in buttons {
            writeln!(s, "        {} = 0x{:X},", name, value).ok();
        }
        writeln!(s, "    }};\n").ok();
    }

    // Build a set of class names to detect collisions with enum names
    let class_names: BTreeSet<String> = classes.iter().map(|c| sanitize_class_name(&c.name)).collect();

    // Forward-declare every class up front so order-of-definition / cyclic
    // references are not a problem.
    let mut declared: BTreeSet<String> = BTreeSet::new();
    for c in classes {
        let sanitized_name = sanitize_class_name(&c.name);
        if declared.insert(sanitized_name.clone()) {
            writeln!(s, "    class {};", sanitized_name).ok();
        }
    }
    writeln!(s).ok();

    // Track emitted enum names to prevent duplicates
    let mut emitted_enums: BTreeSet<String> = BTreeSet::new();

    // Enums first so classes can reference them.
    for e in enums {
        // Determine if enum has negative values
        let has_negative = e.members.iter().any(|m| (m.value as i64) < 0);

        let underlying = match e.alignment {
            1 => if has_negative { "std::int8_t" } else { "std::uint8_t" },
            2 => if has_negative { "std::int16_t" } else { "std::uint16_t" },
            4 => if has_negative { "std::int32_t" } else { "std::uint32_t" },
            8 => if has_negative { "std::int64_t" } else { "std::uint64_t" },
            _ => continue,
        };

        // Check for name collision with classes and append _e suffix if needed
        let enum_name = type_ident(&e.name);
        let mut final_enum_name = if class_names.contains(&enum_name) {
            format!("{}_e", enum_name)
        } else {
            enum_name.clone()
        };

        // Handle duplicate enum names by appending a counter
        let mut counter = 2;
        while emitted_enums.contains(&final_enum_name) {
            final_enum_name = if class_names.contains(&enum_name) {
                format!("{}_e{}", enum_name, counter)
            } else {
                format!("{}_{}", enum_name, counter)
            };
            counter += 1;
        }

        // Mark this enum name as emitted
        emitted_enums.insert(final_enum_name.clone());

        writeln!(s, "    enum class {} : {} {{", final_enum_name, underlying).ok();
        for m in &e.members {
            // Cast to signed for proper display of negative values
            let value = m.value as i64;
            let val_str = if value < 0 {
                format!("{}", value)
            } else {
                format!("{:#X}", m.value as u64)
            };
            let anno = if m.metadata.is_empty() {
                String::new()
            } else {
                format!(" // {}", m.metadata.join(", "))
            };
            writeln!(s, "        {} = {},{}", sanitize_enum_member(&m.name), val_str, anno).ok();
        }
        writeln!(s, "    }};\n").ok();
    }

    // Classes: emit with parent inheritance + SCHEMA_FIELD accessors.
    // Sort classes topologically so base classes are defined before derived classes.
    let sorted_classes = topological_sort_classes(classes);

    for c in &sorted_classes {
        write_class_doc(&mut s, c);
        let sanitized_name = sanitize_class_name(&c.name);

        // Qualify the parent class with its owning sdk::<module> namespace
        // if it was emitted in a different module. This avoids unqualified
        // base class names that may be defined elsewhere (causing C2504).
        let parent = match &c.parent_name {
            Some(raw_parent) => {
                let sanitized_parent = sanitize_class_name(raw_parent);
                if let Some(owner_ns) = type_namespace_map.get(&sanitized_parent) {
                    if owner_ns != &ns {
                        format!(" : public ::{}::{}", owner_ns, sanitized_parent)
                    } else {
                        format!(" : public {}", sanitized_parent)
                    }
                } else {
                    format!(" : public {}", sanitized_parent)
                }
            }
            None => String::new(),
        };

        writeln!(s, "    class {}{} {{", sanitized_name, parent).ok();
        writeln!(s, "    public:").ok();

        // First pass: emit type aliases for fields with commas in their types
        let mut alias_counter = 0;
        let mut field_aliases: Vec<(usize, String)> = Vec::new();
        for (idx, f) in c.fields.iter().enumerate() {
            let cpp_ty = map_schema_type(&f.type_name, &ns, type_namespace_map);
            if cpp_ty.contains(',') {
                let alias_name = format!("_Type{}", alias_counter);
                writeln!(s, "        using {} = {};", alias_name, cpp_ty).ok();
                field_aliases.push((idx, alias_name));
                alias_counter += 1;
            }
        }

        // Second pass: emit SCHEMA_FIELD with type aliases where needed
        for (idx, f) in c.fields.iter().enumerate() {
            let cpp_ty = map_schema_type(&f.type_name, &ns, type_namespace_map);

            // Skip bitfield types - they can't be accessed via SCHEMA_FIELD macro
            if f.type_name.starts_with("bitfield:") {
                writeln!(
                    s,
                    "        // SKIPPED: {} (bitfield type not supported)",
                    f.name,
                )
                .ok();
                continue;
            }

            let safe_ty = field_aliases.iter()
                .find(|(i, _)| *i == idx)
                .map(|(_, alias)| alias.clone())
                .unwrap_or(cpp_ty.clone());
            let anno = if f.metadata.is_empty() {
                String::new()
            } else {
                format!(" [{}]", f.metadata.join(", "))
            };
            writeln!(
                s,
                "        SCHEMA_FIELD({:<32}, {:<48}, {:#X}) // {}{}",
                safe_ty, f.name, f.offset, f.type_name, anno,
            )
            .ok();
        }
        writeln!(s, "    }};\n").ok();
    }

    // Add manual CEconItem class for server.dll (not in schema)
    if ns == "server" {
        writeln!(s, "    // CEconItem").ok();
        writeln!(s, "    //   Manual addition - server-side inventory item").ok();
        writeln!(s, "    //   fields: 11").ok();
        writeln!(s, "    class CEconItem {{").ok();
        writeln!(s, "    public:").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint64_t                   , m_ulID                                          , 0x10) // uint64").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint64_t                   , m_ulOriginalID                                  , 0x18) // uint64").ok();
        writeln!(s, "        SCHEMA_FIELD(void*                           , m_pCustomData                                   , 0x20) // void*").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint32_t                   , m_unAccountID                                   , 0x28) // uint32").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint32_t                   , m_unInventory                                   , 0x2C) // uint32").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint16_t                   , m_unDefIndex                                    , 0x30) // uint16").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint16_t                   , m_nQuality                                      , 0x32) // uint16").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint16_t                   , m_nRarity                                       , 0x32) // uint16").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint16_t                   , m_iItemSet                                      , 0x34) // uint16").ok();
        writeln!(s, "        SCHEMA_FIELD(bool                            , m_bSOUpdateFrame                                , 0x38) // bool").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint32_t                   , m_unFlags                                       , 0x3C) // uint32").ok();
        writeln!(s, "    }};\n").ok();
    }

    // Manual c_mesh_draw_primitive / c_mesh_primitive_output_buffer for scenesystem.dll
    // (not in schema — internal render primitives from GeneratePrimitives)
    if ns == "scenesystem" {
        writeln!(s, "    // c_mesh_draw_primitive — per-element mesh draw primitive (0x68 bytes)").ok();
        writeln!(s, "    struct c_mesh_draw_primitive {{").ok();
        writeln!(s, "        std::byte _pad0[0x20];").ok();
        writeln!(s, "        void* m_material;          // +0x20").ok();
        writeln!(s, "        std::byte _pad1[0x28];").ok();
        writeln!(s, "        std::uint32_t m_tint_color;   // +0x50 — packed RGBA uint32 (0xAABBGGRR)").ok();
        writeln!(s, "        float m_alpha_scale;       // +0x54 — alpha scale (default 1.0f)").ok();
        writeln!(s, "        std::byte _pad3[0x62 - 0x58];").ok();
        writeln!(s, "        std::uint16_t m_render_flags;  // +0x62").ok();
        writeln!(s, "        std::uint16_t m_render_flags2; // +0x64").ok();
        writeln!(s, "        std::byte _pad4[0x68 - 0x66];").ok();
        writeln!(s, "    }};\n").ok();

        writeln!(s, "    // c_mesh_primitive_output_buffer — output buffer passed to GeneratePrimitives").ok();
        writeln!(s, "    struct c_mesh_primitive_output_buffer {{").ok();
        writeln!(s, "        c_mesh_draw_primitive* m_out;              // +0x00").ok();
        writeln!(s, "        int m_max_output_primitives;               // +0x08").ok();
        writeln!(s, "        int m_start_primitive;                     // +0x0C").ok();
        writeln!(s, "    }};\n").ok();

// CSceneAnimatableObject — the `this` parameter of GeneratePrimitives
        writeln!(s, "    // CSceneAnimatableObject — owner of a scene object hierarchy").ok();
        writeln!(s, "    struct CSceneAnimatableObject {{").ok();
        writeln!(s, "        std::byte _pad0[0xC0];                    // +0x00 padding").ok();
        writeln!(s, "        CEntityHandle m_hOwner;                    // +0xC0 entity handle").ok();
        writeln!(s, "    }};\n").ok();
    }

    // Manual types for materialsystem2.dll - not in schema, internal material system types
    if ns == "materialsystem2" {
        writeln!(s, "    // KV3 ID type - used for material system KV3 loading").ok();
        writeln!(s, "    struct kv3_id_t {{").ok();
        writeln!(s, "        const char* m_pString;").ok();
        writeln!(s, "        std::uint64_t m_hash1;").ok();
        writeln!(s, "        std::uint64_t m_hash2;").ok();
        writeln!(s, "    }};\n").ok();
    }

    writeln!(s, "}} // namespace {}", ns).ok();
    s
}

fn write_banner(
    s: &mut String,
    module: &str,
    classes: usize,
    enums: usize,
    build_number: Option<u32>,
    timestamp: &str,
) {
    let _ = build_number;  // intentionally unused — see manifest.json
    writeln!(s, "// Generated by cs2-sdk — https://cs2-sdk.com").ok();
    writeln!(s, "//").ok();
    writeln!(s, "// module:        {}", module).ok();
    writeln!(s, "// classes:       {}", classes).ok();
    writeln!(s, "// enums:         {}", enums).ok();
    writeln!(s, "// generated_at:  {}", timestamp).ok();
    writeln!(s, "//").ok();
    writeln!(s, "// Use:").ok();
    writeln!(s, "//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);").ok();
    writeln!(s, "//   pawn->m_iHealth() = 100;").ok();
    writeln!(s).ok();
}

/// Machine-readable structured schema dump — `module -> { classes, enums }`,
/// each class with size/alignment/metadata and each field with its offset,
/// type and annotation names. Powers the site's class browser and `/api`.
pub fn render_schemas_json(schemas: &SchemaMap) -> String {
    use serde_json::{Map, Value, json};

    let meta_str = |m: &crate::analysis::ClassMetadata| -> String {
        match m {
            crate::analysis::ClassMetadata::NetworkVarNames { name, type_name } => {
                format!("MNetworkVarNames {} {}", type_name, name)
            }
            crate::analysis::ClassMetadata::NetworkChangeCallback { name } => {
                format!("MNetworkChangeCallback {}", name)
            }
            crate::analysis::ClassMetadata::Unknown { name } => name.clone(),
        }
    };

    let mut root = Map::new();
    for (module, (classes, enums)) in schemas {
        let classes_json: Vec<Value> = classes
            .iter()
            .map(|c| {
                json!({
                    "name": c.name,
                    "parent": c.parent_name,
                    "size": c.size,
                    "metadata": c.metadata.iter().map(&meta_str).collect::<Vec<_>>(),
                    "fields": c.fields.iter().map(|f| json!({
                        "name": f.name,
                        "type": f.type_name,
                        "offset": f.offset,
                        "metadata": f.metadata,
                    })).collect::<Vec<_>>(),
                })
            })
            .collect();

        let enums_json: Vec<Value> = enums
            .iter()
            .map(|e| {
                json!({
                    "name": e.name,
                    "alignment": e.alignment,
                    "members": e.members.iter().map(|m| json!({
                        "name": m.name,
                        "value": m.value,
                        "metadata": m.metadata,
                    })).collect::<Vec<_>>(),
                })
            })
            .collect();

        root.insert(
            module.clone(),
            json!({ "classes": classes_json, "enums": enums_json }),
        );
    }

    serde_json::to_string_pretty(&Value::Object(root)).unwrap_or_default()
}

fn write_class_doc(s: &mut String, c: &Class) {
    writeln!(s, "    // {}", c.name).ok();
    if let Some(parent) = &c.parent_name {
        writeln!(s, "    //   parent: {}", parent).ok();
    }
    writeln!(s, "    //   fields: {}", c.fields.len()).ok();
    if c.size > 0 {
        writeln!(s, "    //   size: {:#X}", c.size).ok();
    }
    // Class-level schema annotations (MNetworkVarNames, MClassHasEntityLimitedDataDesc, ...)
    for m in &c.metadata {
        match m {
            crate::analysis::ClassMetadata::NetworkVarNames { name, type_name } => {
                writeln!(s, "    //   @MNetworkVarNames {} {}", type_name, name).ok();
            }
            crate::analysis::ClassMetadata::NetworkChangeCallback { name } => {
                writeln!(s, "    //   @MNetworkChangeCallback {}", name).ok();
            }
            crate::analysis::ClassMetadata::Unknown { name } => {
                writeln!(s, "    //   @{}", name).ok();
            }
        }
    }
}

/// Map a Source 2 schema type string to its canonical C++ equivalent.
///
/// We intentionally err on the side of "leave as-is" — anything we don't
/// understand is wrapped in a forward-decl-friendly pointer or returned
/// verbatim. This keeps the header useful even for types we haven't yet
/// hand-mapped.
fn map_schema_type(
    raw: &str,
    current_ns: &str,
    type_namespace_map: &BTreeMap<String, String>,
) -> String {
    let t = raw.trim();

    // Handle array types: Type[N] -> Type (the SCHEMA_FIELD macro handles array access)
    if let Some(bracket_pos) = t.find('[') {
        let base_type = &t[..bracket_pos];
        return map_schema_type(base_type, current_ns, type_namespace_map);
    }

    let mapped = match t {
        "bool" => "bool".into(),
        "char" => "char".into(),
        "int8"  | "int8_t"   => "std::int8_t".into(),
        "uint8" | "uint8_t"  => "std::uint8_t".into(),
        "int16" | "int16_t"  => "std::int16_t".into(),
        "uint16"| "uint16_t" => "std::uint16_t".into(),
        "int32" | "int32_t"  => "std::int32_t".into(),
        "uint32"| "uint32_t" => "std::uint32_t".into(),
        "int64" | "int64_t"  => "std::int64_t".into(),
        "uint64"| "uint64_t" => "std::uint64_t".into(),
        "float32" | "float"  => "float".into(),
        "float64" | "double" => "double".into(),
        "Vector"             => "::Vector".into(),
        "Vector2D"           => "::Vector2D".into(),
        "Vector4D"           => "::Vector4D".into(),
        "QAngle"             => "::QAngle".into(),
        "Quaternion"         => "::Quaternion".into(),
        "Color"              => "::Color".into(),
        "CUtlString"         => "::CUtlString".into(),
        "CUtlSymbolLarge"    => "::CUtlSymbolLarge".into(),
        "CUtlBinaryBlock"    => "::CUtlBinaryBlock".into(),
        "matrix3x4_t"        => "::matrix3x4_t".into(),
        "AABB_t"             => "::AABB_t".into(),
        "CRenderBufferBinding" => "::CRenderBufferBinding".into(),
        // Time types
        "GameTime_t"         => "::GameTime_t".into(),
        "GameTick_t"         => "::GameTick_t".into(),
        // Symbol/ID types
        "PulseSymbol_t"      => "::PulseSymbol_t".into(),
        "PulseDocNodeID_t"   => "::PulseDocNodeID_t".into(),
        "PulseRuntimeChunkIndex_t" => "::PulseRuntimeChunkIndex_t".into(),
        "PulseRegisterMap_t" => "::PulseRegisterMap_t".into(),
        "WorldGroupId_t"     => "::WorldGroupId_t".into(),
        "ChangeAccessorFieldPathIndex_t" => "::ChangeAccessorFieldPathIndex_t".into(),
        _ => {
            // Templated containers are extremely common in the schema:
            // CHandle< C_X >, CUtlVector< T >, CNetworkedQuantizedFloat, ...
            // Need to sanitize nested class names in template parameters but preserve std::
            // e.g., CUtlVector<CPulseCell_Timeline::TimelineEvent_t> -> CUtlVector<CPulseCell_Timeline_TimelineEvent_t>
            // but std::pair<A,B> stays as std::pair<A,B>

            // Simple approach: replace all :: with _ EXCEPT when preceded by "std"
            let mut result = String::new();
            let chars: Vec<char> = t.chars().collect();
            let mut i = 0;

            while i < chars.len() {
                if i + 1 < chars.len() && chars[i] == ':' && chars[i + 1] == ':' {
                    // Found ::, check if it's std::
                    let is_std = i >= 3 &&
                                 chars[i-3] == 's' &&
                                 chars[i-2] == 't' &&
                                 chars[i-1] == 'd';

                    if is_std {
                        // Keep std::
                        result.push_str("::");
                    } else {
                        // Replace :: with _
                        result.push('_');
                    }
                    i += 2; // Skip both colons
                } else {
                    result.push(chars[i]);
                    i += 1;
                }
            }

            result
        }
    };

    qualify_cross_module_type_refs(&mapped, current_ns, type_namespace_map)
}

fn qualify_cross_module_type_refs(
    cpp_type: &str,
    current_ns: &str,
    type_namespace_map: &BTreeMap<String, String>,
) -> String {
    let chars: Vec<char> = cpp_type.chars().collect();
    let mut out = String::with_capacity(cpp_type.len());
    let mut i = 0;

    while i < chars.len() {
        if chars[i].is_ascii_alphabetic() || chars[i] == '_' {
            let start = i;
            i += 1;
            while i < chars.len() && (chars[i].is_ascii_alphanumeric() || chars[i] == '_') {
                i += 1;
            }

            let token: String = chars[start..i].iter().collect();
            let scoped = start >= 2 && chars[start - 2] == ':' && chars[start - 1] == ':';
            if !scoped {
                if let Some(owner_ns) = type_namespace_map.get(&token) {
                    if owner_ns != current_ns {
                        out.push_str("::");
                        out.push_str(owner_ns);
                        out.push_str("::");
                        out.push_str(&token);
                        continue;
                    }
                }
            }

            out.push_str(&token);
            continue;
        }

        out.push(chars[i]);
        i += 1;
    }

    out
}

fn sanitize_enum_member(raw: &str) -> String {
    let mut s = String::with_capacity(raw.len());
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            s.push(c);
        } else {
            s.push('_');
        }
    }
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s.insert(0, '_');
    }
    s
}

/// Sanitize class names by replacing `::` with `_` to avoid nested class syntax issues.
/// For example, `CPulseCell_Timeline::TimelineEvent_t` becomes `CPulseCell_Timeline_TimelineEvent_t`.
fn sanitize_class_name(raw: &str) -> String {
    raw.replace("::", "_")
}
